DEFAULT_CATEGORIES = [
    {"slug": "world", "name": "World News", "order": 0},
    {"slug": "us", "name": "US News", "order": 1},
    {"slug": "europe", "name": "Europe", "order": 2},
    {"slug": "tech", "name": "Tech", "order": 3},
    {"slug": "ai", "name": "AI / ML", "order": 4},
    {"slug": "security", "name": "Security", "order": 5},
    {"slug": "science", "name": "Science", "order": 6},
    {"slug": "finance", "name": "Finance", "order": 7},
    {"slug": "dev", "name": "Dev & Programming", "order": 8},
    {"slug": "linux", "name": "Linux / Open Source", "order": 9},
    {"slug": "startups", "name": "Startups & VC", "order": 10},
    {"slug": "gaming", "name": "Gaming", "order": 11},
    {"slug": "design", "name": "Design / Product", "order": 12},
    {"slug": "media", "name": "Media / Blogs", "order": 13},
    {"slug": "mideast", "name": "Middle East", "order": 14},
    {"slug": "asia", "name": "Asia-Pacific", "order": 15},
    {"slug": "southasia", "name": "South Asia", "order": 16},
    {"slug": "africa", "name": "Africa", "order": 17},
    {"slug": "latam", "name": "Latin America", "order": 18},
    {"slug": "ru", "name": "Русские", "order": 19},
]

DEFAULT_FEEDS = [
    # ── World News ────────────────────────────────────────
    {"title": "AP News Top", "url": "https://feedx.net/rss/ap.xml", "category": "world"},
    {"title": "Al Jazeera", "url": "https://www.aljazeera.com/xml/rss/all.xml", "category": "world"},
    {"title": "BBC News - World", "url": "https://feeds.bbci.co.uk/news/world/rss.xml", "category": "world"},
    {"title": "CNN", "url": "http://rss.cnn.com/rss/edition.rss", "category": "world"},
    {"title": "DW News", "url": "https://rss.dw.com/rdf/rss-en-all", "category": "world"},
    {"title": "France 24", "url": "https://www.france24.com/en/rss", "category": "world"},
    {"title": "NPR World", "url": "https://feeds.npr.org/1004/rss.xml", "category": "world"},
    {"title": "Reuters (via Google)", "url": "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB", "category": "world"},
    {"title": "South China Morning Post", "url": "https://www.scmp.com/rss/91/feed", "category": "world"},
    {"title": "The Guardian - World", "url": "https://www.theguardian.com/world/rss", "category": "world"},
    {"title": "The Intercept", "url": "https://theintercept.com/feed/?rss", "category": "world"},
    {"title": "Times of India", "url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "category": "world"},
    {"title": "UN News", "url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "category": "world"},
    # ── US News ───────────────────────────────────────────
    {"title": "ABC News", "url": "https://abcnews.go.com/abcnews/topstories", "category": "us"},
    {"title": "BBC News - US & Canada", "url": "https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml", "category": "us"},
    {"title": "CBS News", "url": "https://www.cbsnews.com/latest/rss/main", "category": "us"},
    {"title": "NBC News", "url": "https://feeds.nbcnews.com/nbcnews/public/news", "category": "us"},
    {"title": "NPR National", "url": "https://feeds.npr.org/1003/rss.xml", "category": "us"},
    {"title": "Politico", "url": "https://rss.politico.com/politics-news.xml", "category": "us"},
    {"title": "The Guardian - US", "url": "https://www.theguardian.com/us-news/rss", "category": "us"},
    # ── Europe ────────────────────────────────────────────
    {"title": "BBC News - Europe", "url": "https://feeds.bbci.co.uk/news/world/europe/rss.xml", "category": "europe"},
    {"title": "EurActiv", "url": "https://www.euractiv.com/feed/", "category": "europe"},
    {"title": "Euronews English", "url": "https://www.euronews.com/rss?format=mrss&level=theme&name=news", "category": "europe"},
    {"title": "Le Monde English", "url": "https://www.lemonde.fr/en/rss/une.xml", "category": "europe"},
    {"title": "Politico EU", "url": "https://www.politico.eu/feed/", "category": "europe"},
    {"title": "Spiegel International", "url": "https://www.spiegel.de/international/index.rss", "category": "europe"},
    {"title": "The Guardian - Europe", "url": "https://www.theguardian.com/world/europe-news/rss", "category": "europe"},
    # ── Tech ──────────────────────────────────────────────
    {"title": "9to5Google", "url": "https://9to5google.com/feed/", "category": "tech"},
    {"title": "9to5Mac", "url": "https://9to5mac.com/feed/", "category": "tech"},
    {"title": "Android Authority", "url": "https://www.androidauthority.com/feed/", "category": "tech"},
    {"title": "Ars Technica", "url": "https://feeds.arstechnica.com/arstechnica/index", "category": "tech"},
    {"title": "Daring Fireball", "url": "https://daringfireball.net/feeds/main", "category": "tech"},
    {"title": "Engadget", "url": "https://www.engadget.com/rss.xml", "category": "tech"},
    {"title": "Gizmodo", "url": "https://gizmodo.com/feed", "category": "tech"},
    {"title": "Hacker News", "url": "https://hnrss.org/frontpage", "category": "tech"},
    {"title": "Lobste.rs", "url": "https://lobste.rs/rss", "category": "tech"},
    {"title": "MIT Tech Review", "url": "https://www.technologyreview.com/feed/", "category": "tech"},
    {"title": "MacRumors", "url": "https://feeds.macrumors.com/MacRumors-All", "category": "tech"},
    {"title": "Slashdot", "url": "https://rss.slashdot.org/Slashdot/slashdotMain", "category": "tech"},
    {"title": "TechCrunch", "url": "https://techcrunch.com/feed", "category": "tech"},
    {"title": "The Register", "url": "https://www.theregister.com/headlines.atom", "category": "tech"},
    {"title": "The Verge", "url": "https://www.theverge.com/rss/index.xml", "category": "tech"},
    {"title": "Tom's Hardware", "url": "https://www.tomshardware.com/feeds/all", "category": "tech"},
    {"title": "Wired", "url": "https://www.wired.com/feed/rss", "category": "tech"},
    {"title": "ZDNet", "url": "https://www.zdnet.com/news/rss.xml", "category": "tech"},
    # ── AI / ML ───────────────────────────────────────────
    {"title": "Ahead of AI", "url": "https://magazine.sebastianraschka.com/feed", "category": "ai"},
    {"title": "DeepMind Blog", "url": "https://deepmind.google/blog/rss.xml", "category": "ai"},
    {"title": "Google AI Blog", "url": "https://blog.google/technology/ai/rss/", "category": "ai"},
    {"title": "Hugging Face Blog", "url": "https://huggingface.co/blog/feed.xml", "category": "ai"},
    {"title": "Import AI", "url": "https://importai.substack.com/feed", "category": "ai"},
    {"title": "MIT News - AI", "url": "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml", "category": "ai"},
    {"title": "OpenAI Blog", "url": "https://openai.com/blog/rss.xml", "category": "ai"},
    {"title": "The Gradient", "url": "https://thegradient.pub/rss/", "category": "ai"},
    {"title": "Towards Data Science", "url": "https://towardsdatascience.com/feed", "category": "ai"},
    {"title": "VentureBeat AI", "url": "https://venturebeat.com/category/ai/feed/", "category": "ai"},
    # ── Security ──────────────────────────────────────────
    {"title": "Bleeping Computer", "url": "https://www.bleepingcomputer.com/feed/", "category": "security"},
    {"title": "Krebs on Security", "url": "https://krebsonsecurity.com/feed/", "category": "security"},
    {"title": "SANS ISC", "url": "https://isc.sans.edu/rssfeed.xml", "category": "security"},
    {"title": "Schneier on Security", "url": "https://www.schneier.com/feed/atom/", "category": "security"},
    {"title": "Security Week", "url": "https://www.securityweek.com/feed/", "category": "security"},
    {"title": "The Hacker News (Security)", "url": "https://feeds.feedburner.com/TheHackersNews", "category": "security"},
    {"title": "Threatpost", "url": "https://threatpost.com/feed/", "category": "security"},
    {"title": "Trail of Bits", "url": "https://blog.trailofbits.com/feed/", "category": "security"},
    # ── Science ───────────────────────────────────────────
    {"title": "Aeon", "url": "https://aeon.co/feed.rss", "category": "science"},
    {"title": "Ars Technica Science", "url": "https://feeds.arstechnica.com/arstechnica/science", "category": "science"},
    {"title": "Live Science", "url": "https://www.livescience.com/feeds/all", "category": "science"},
    {"title": "NASA Breaking News", "url": "https://www.nasa.gov/news-release/feed/", "category": "science"},
    {"title": "Nature", "url": "https://www.nature.com/nature.rss", "category": "science"},
    {"title": "Nautilus", "url": "https://nautil.us/feed/", "category": "science"},
    {"title": "New Scientist", "url": "https://www.newscientist.com/feed/home/", "category": "science"},
    {"title": "Phys.org", "url": "https://phys.org/rss-feed/", "category": "science"},
    {"title": "Quanta Magazine", "url": "https://www.quantamagazine.org/feed/", "category": "science"},
    {"title": "STAT News", "url": "https://www.statnews.com/feed/", "category": "science"},
    {"title": "Science Daily", "url": "https://www.sciencedaily.com/rss/all.xml", "category": "science"},
    {"title": "Smithsonian", "url": "https://www.smithsonianmag.com/rss/latest_articles/", "category": "science"},
    {"title": "Space.com", "url": "https://www.space.com/feeds/all", "category": "science"},
    # ── Finance ───────────────────────────────────────────
    {"title": "Calculated Risk", "url": "https://www.calculatedriskblog.com/feeds/posts/default?alt=rss", "category": "finance"},
    {"title": "CNBC Top News", "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114", "category": "finance"},
    {"title": "Coindesk", "url": "https://www.coindesk.com/arc/outboundfeeds/rss/", "category": "finance"},
    {"title": "CoinTelegraph", "url": "https://cointelegraph.com/rss", "category": "finance"},
    {"title": "Decrypt", "url": "https://decrypt.co/feed", "category": "finance"},
    {"title": "Matt Levine", "url": "https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss", "category": "finance"},
    {"title": "Naked Capitalism", "url": "https://www.nakedcapitalism.com/feed", "category": "finance"},
    {"title": "Wolf Street", "url": "https://wolfstreet.com/feed/", "category": "finance"},
    {"title": "Yahoo Finance", "url": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=^GSPC&region=US&lang=en-US", "category": "finance"},
    # ── Dev & Programming ─────────────────────────────────
    {"title": "Astro Blog", "url": "https://astro.build/rss.xml", "category": "dev"},
    {"title": "Chrome Developers", "url": "https://developer.chrome.com/blog/feed.xml", "category": "dev"},
    {"title": "Cloudflare Blog", "url": "https://blog.cloudflare.com/rss/", "category": "dev"},
    {"title": "Dan Abramov", "url": "https://overreacted.io/rss.xml", "category": "dev"},
    {"title": "Deno Blog", "url": "https://deno.com/feed", "category": "dev"},
    {"title": "Deterministic Simulation", "url": "https://deterministic.space/feed.xml", "category": "dev"},
    {"title": "Dev.to", "url": "https://dev.to/feed", "category": "dev"},
    {"title": "Docker Blog", "url": "https://www.docker.com/feed/", "category": "dev"},
    {"title": "Dropbox Tech", "url": "https://dropbox.tech/feed", "category": "dev"},
    {"title": "Eli Bendersky", "url": "https://eli.thegreenplace.net/feeds/all.atom.xml", "category": "dev"},
    {"title": "Engineering at Meta", "url": "https://engineering.fb.com/feed/", "category": "dev"},
    {"title": "Fly.io Blog", "url": "https://fly.io/blog/feed.xml", "category": "dev"},
    {"title": "GitHub Blog", "url": "https://github.blog/feed/", "category": "dev"},
    {"title": "GitHub Engineering", "url": "https://github.blog/engineering/feed/", "category": "dev"},
    {"title": "Go Blog", "url": "https://go.dev/blog/feed.atom", "category": "dev"},
    {"title": "HashiCorp Blog", "url": "https://www.hashicorp.com/blog/feed.xml", "category": "dev"},
    {"title": "Julia Evans", "url": "https://jvns.ca/atom.xml", "category": "dev"},
    {"title": "Kubernetes Blog", "url": "https://kubernetes.io/feed.xml", "category": "dev"},
    {"title": "Martin Fowler", "url": "https://martinfowler.com/feed.atom", "category": "dev"},
    {"title": "Mitchell Hashimoto", "url": "https://mitchellh.com/feed.xml", "category": "dev"},
    {"title": "Mozilla Hacks", "url": "https://hacks.mozilla.org/feed/", "category": "dev"},
    {"title": "Node.js Blog", "url": "https://nodejs.org/en/feed/blog.xml", "category": "dev"},
    {"title": "Pragmatic Engineer", "url": "https://newsletter.pragmaticengineer.com/feed", "category": "dev"},
    {"title": "Python Insider", "url": "https://blog.python.org/feeds/posts/default?alt=rss", "category": "dev"},
    {"title": "Rust Blog", "url": "https://blog.rust-lang.org/feed.xml", "category": "dev"},
    {"title": "Simon Willison", "url": "https://simonwillison.net/atom/everything/", "category": "dev"},
    {"title": "Spotify Engineering", "url": "https://engineering.atspotify.com/feed/", "category": "dev"},
    {"title": "Stripe Blog", "url": "https://stripe.com/blog/feed.rss", "category": "dev"},
    {"title": "Svelte Blog", "url": "https://svelte.dev/blog/rss.xml", "category": "dev"},
    {"title": "Tailwind Blog", "url": "https://tailwindcss.com/feeds/feed.xml", "category": "dev"},
    {"title": "Thorsten Ball", "url": "https://registerspill.thorstenball.com/feed", "category": "dev"},
    {"title": "Vercel Blog", "url": "https://vercel.com/atom", "category": "dev"},
    # ── Linux / Open Source ───────────────────────────────
    {"title": "Fedora Magazine", "url": "https://fedoramagazine.org/feed/", "category": "linux"},
    {"title": "It's FOSS", "url": "https://itsfoss.com/feed/", "category": "linux"},
    {"title": "LWN.net", "url": "https://lwn.net/headlines/rss", "category": "linux"},
    {"title": "Linux Today", "url": "https://www.linuxtoday.com/feed/", "category": "linux"},
    {"title": "OMG Ubuntu", "url": "https://www.omgubuntu.co.uk/feed", "category": "linux"},
    # ── Startups & VC ─────────────────────────────────────
    {"title": "Both Sides of Table", "url": "https://bothsidesofthetable.com/feed", "category": "startups"},
    {"title": "Paul Graham Essays", "url": "http://www.aaronsw.com/2002/feeds/pgessays.rss", "category": "startups"},
    {"title": "SaaStr", "url": "https://www.saastr.com/feed/", "category": "startups"},
    {"title": "Sequoia Capital", "url": "https://www.sequoiacap.com/feed/", "category": "startups"},
    {"title": "Y Combinator Blog", "url": "https://www.ycombinator.com/blog/rss/", "category": "startups"},
    {"title": "a16z Future", "url": "https://future.a16z.com/feed/", "category": "startups"},
    # ── Gaming ────────────────────────────────────────────
    {"title": "Eurogamer", "url": "https://www.eurogamer.net/feed", "category": "gaming"},
    {"title": "IGN", "url": "https://feeds.feedburner.com/ign/all", "category": "gaming"},
    {"title": "Kotaku", "url": "https://kotaku.com/rss", "category": "gaming"},
    {"title": "PC Gamer", "url": "https://www.pcgamer.com/rss/", "category": "gaming"},
    {"title": "Polygon", "url": "https://www.polygon.com/rss/index.xml", "category": "gaming"},
    {"title": "Rock Paper Shotgun", "url": "https://www.rockpapershotgun.com/feed", "category": "gaming"},
    # ── Design / Product ──────────────────────────────────
    {"title": "A List Apart", "url": "https://alistapart.com/main/feed/", "category": "design"},
    {"title": "CSS-Tricks", "url": "https://css-tricks.com/feed/", "category": "design"},
    {"title": "Sidebar.io", "url": "https://sidebar.io/feed.xml", "category": "design"},
    {"title": "Smashing Magazine", "url": "https://www.smashingmagazine.com/feed/", "category": "design"},
    {"title": "UX Collective", "url": "https://uxdesign.cc/feed", "category": "design"},
    # ── Media / Blogs ─────────────────────────────────────
    {"title": "404 Media", "url": "https://www.404media.co/rss/", "category": "media"},
    {"title": "Benedict Evans", "url": "https://www.ben-evans.com/benedictevans?format=rss", "category": "media"},
    {"title": "Changelog", "url": "https://changelog.com/feed", "category": "media"},
    {"title": "Defector", "url": "https://defector.com/rss", "category": "media"},
    {"title": "Longreads", "url": "https://longreads.com/feed/", "category": "media"},
    {"title": "Rest of World", "url": "https://restofworld.org/feed/latest/", "category": "media"},
    {"title": "Stratechery", "url": "https://stratechery.com/feed/", "category": "media"},
    {"title": "The Conversation", "url": "https://theconversation.com/us/articles.atom", "category": "media"},
    {"title": "Wait But Why", "url": "https://waitbutwhy.com/feed", "category": "media"},
    # ── Middle East ───────────────────────────────────────
    {"title": "Al-Monitor", "url": "https://www.al-monitor.com/rss", "category": "mideast"},
    {"title": "Arab News", "url": "https://www.arabnews.com/taxonomy/term/2/feed", "category": "mideast"},
    {"title": "Israel Hayom", "url": "https://www.israelhayom.com/feed/", "category": "mideast"},
    {"title": "Jerusalem Post", "url": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", "category": "mideast"},
    {"title": "Middle East Eye", "url": "https://www.middleeasteye.net/rss", "category": "mideast"},
    {"title": "Middle East Monitor", "url": "https://www.middleeastmonitor.com/feed/", "category": "mideast"},
    {"title": "Daily Sabah", "url": "https://www.dailysabah.com/rssfeed/latest", "category": "mideast"},
    {"title": "Hurriyet Daily News", "url": "https://www.hurriyetdailynews.com/rss.aspx", "category": "mideast"},
    {"title": "Times of Israel", "url": "https://www.timesofisrael.com/feed/", "category": "mideast"},
    # ── Asia-Pacific ─────────────────────────────────────
    {"title": "ABC Australia", "url": "https://www.abc.net.au/news/feed/2942460/rss.xml", "category": "asia"},
    {"title": "Bangkok Post", "url": "https://www.bangkokpost.com/rss/data/topstories.xml", "category": "asia"},
    {"title": "CGTN", "url": "https://www.cgtn.com/subscribe/rss/section/world.xml", "category": "asia"},
    {"title": "Channel NewsAsia", "url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml", "category": "asia"},
    {"title": "China Daily", "url": "https://www.chinadaily.com.cn/rss/world_rss.xml", "category": "asia"},
    {"title": "Japan Times", "url": "https://www.japantimes.co.jp/feed/", "category": "asia"},
    {"title": "Korea Times", "url": "https://www.koreatimes.co.kr/www/rss/rss.xml", "category": "asia"},
    {"title": "NHK World", "url": "https://www3.nhk.or.jp/nhkworld/data/en/news/backstory/rss.xml", "category": "asia"},
    {"title": "Nikkei Asia", "url": "https://asia.nikkei.com/rss/feed/nar", "category": "asia"},
    {"title": "Nippon.com", "url": "https://www.nippon.com/en/feed/", "category": "asia"},
    {"title": "RNZ New Zealand", "url": "https://www.rnz.co.nz/rss/national.xml", "category": "asia"},
    {"title": "Taipei Times", "url": "https://www.taipeitimes.com/xml/index.rss", "category": "asia"},
    {"title": "Yonhap News", "url": "https://en.yna.co.kr/RSS/news.xml", "category": "asia"},
    # ── South Asia ───────────────────────────────────────
    {"title": "Dawn", "url": "https://www.dawn.com/feeds/home", "category": "southasia"},
    {"title": "NDTV", "url": "https://feeds.feedburner.com/NDTV-LatestNews", "category": "southasia"},
    {"title": "The Hindu", "url": "https://www.thehindu.com/feeder/default.rss", "category": "southasia"},
    # ── Africa ───────────────────────────────────────────
    {"title": "Africanews", "url": "https://www.africanews.com/feed/rss", "category": "africa"},
    {"title": "Mail & Guardian", "url": "https://mg.co.za/feed/", "category": "africa"},
    {"title": "News24 South Africa", "url": "https://feeds.news24.com/articles/news24/TopStories/rss", "category": "africa"},
    {"title": "Premium Times Nigeria", "url": "https://www.premiumtimesng.com/feed", "category": "africa"},
    {"title": "The East African", "url": "https://www.theeastafrican.co.ke/rss.xml", "category": "africa"},
    # ── Latin America ────────────────────────────────────
    {"title": "Global Voices", "url": "https://globalvoices.org/feed/", "category": "latam"},
    {"title": "MercoPress", "url": "https://en.mercopress.com/rss", "category": "latam"},
    # ── Русские ───────────────────────────────────────────
    {"title": "3DNews", "url": "https://3dnews.ru/breaking/rss/", "category": "ru"},
    {"title": "N+1", "url": "https://nplus1.ru/rss", "category": "ru"},
    {"title": "OpenNET", "url": "https://www.opennet.ru/opennews/opennews_all_utf.rss", "category": "ru"},
    {"title": "iXBT", "url": "https://www.ixbt.com/export/news.rss", "category": "ru"},
    {"title": "Медуза", "url": "https://meduza.io/rss/all", "category": "ru"},
    {"title": "Хабр", "url": "https://habr.com/ru/rss/articles/?fl=ru", "category": "ru"},
]
