# Generated by Django 6.0.3 on 2026-03-24 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('feeds', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='location.country'),
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feed',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='core.language'),
        ),
        migrations.AddField(
            model_name='feed',
            name='reliability',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feed',
            name='website',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
