# Generated by Django 4.2.29 on 2026-03-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('starred', models.BooleanField(db_index=True, default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feed')),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['feed', 'published'], name='news_articl_feed_id_a65e5a_idx')],
            },
        ),
    ]
