# Generated by Django 4.2.29 on 2026-03-17 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_remove_digestsection_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='news.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='news_articl_article_fdf548_idx')],
                'unique_together': {('article', 'chunk_index')},
            },
        ),
    ]
