# Generated by Django 4.2.29 on 2026-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_embedded_articlechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=300),
        ),
    ]
