# Generated by Django 4.2.29 on 2026-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_fetched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
