# Generated by Django 4.2.29 on 2026-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_add_content_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extract_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
