# Generated by Django 4.2.29 on 2026-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_add_extract_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rss_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
