# Generated by Django 4.2.29 on 2026-03-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_add_rss_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('search_queries', models.JSONField(default=list)),
                ('chunks_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deep Dive',
                'verbose_name_plural': 'Deep Dives',
            },
        ),
        # These columns/tables were already dropped manually, so use SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='digestsection',
                    name='articles',
                ),
                migrations.RemoveField(
                    model_name='digestsection',
                    name='summary',
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='digest_items', to='news.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.digestsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeepDiveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('deep_dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.deepdive')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='deepdive',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dives', to='news.digestitem'),
        ),
    ]
