# Generated by Django 4.2.29 on 2026-03-18 17:54

from django.db import migrations, models


def set_existing_digests_to_uk(apps, schema_editor):
    Digest = apps.get_model("news", "Digest")
    Digest.objects.all().update(language="uk")


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_pgvector_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.RunPython(set_existing_digests_to_uk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='digest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='digest',
            unique_together={('date', 'language')},
        ),
    ]
