# Generated by Django 6.0.3 on 2026-03-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_digest_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digestsection',
            options={'ordering': ['-freshness', 'order']},
        ),
        migrations.AddField(
            model_name='digestsection',
            name='freshness',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
