# Generated by Django 6.0.3 on 2026-03-19 07:04

from django.db import migrations
from django.db.models import Max


def backfill_freshness(apps, schema_editor):
    DigestSection = apps.get_model("news", "DigestSection")
    Article = apps.get_model("news", "Article")

    for section in DigestSection.objects.all():
        newest = (
            Article.objects
            .filter(digest_items__section=section, published__isnull=False)
            .aggregate(newest=Max("published"))["newest"]
        )
        if newest:
            section.freshness = newest.timestamp()
            section.save(update_fields=["freshness"])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_digestsection_options_digestsection_freshness'),
    ]

    operations = [
        migrations.RunPython(backfill_freshness, migrations.RunPython.noop),
    ]
