# Generated by Django 6.0.3 on 2026-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_backfill_freshness'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestitem',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
