# Generated by Django 6.0.3 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_digesttopic_id_alter_topicembedding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='digestitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
