# Generated by Django 6.0.3 on 2026-03-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_add_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images_downloaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('image', models.ImageField(upload_to='articles/%Y/%m/')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.article')),
            ],
            options={
                'unique_together': {('article', 'source_url')},
            },
        ),
        migrations.AddField(
            model_name='digestitem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='news.articleimage'),
        ),
    ]
