# Generated by Django 6.0.3 on 2026-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_article_images_downloaded_articleimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images_downloaded',
        ),
        migrations.RemoveField(
            model_name='digestitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='downloaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
