# Generated by Django 6.0.3 on 2026-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_remove_article_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
