# Generated by Django 6.0.3 on 2026-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_articleimage_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='factuality',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('mixed', 'Mixed'), ('low', 'Low')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='feed',
            name='lean',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center_left', 'Center-Left'), ('center', 'Center'), ('center_right', 'Center-Right'), ('right', 'Right')], db_index=True, default='', max_length=20),
        ),
    ]
