# Generated by Django 6.0.3 on 2026-03-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digest', '0001_initial'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('search_queries', models.JSONField(default=list)),
                ('chunks_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dives', to='digest.digestitem')),
            ],
            options={
                'verbose_name': 'Deep Dive',
                'verbose_name_plural': 'Deep Dives',
            },
        ),
        migrations.CreateModel(
            name='DeepDiveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.article')),
                ('deep_dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='deep_dive.deepdive')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
