# Generated by Django 6.0.3 on 2026-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('digest', 'Digest Generation'), ('research', 'Research'), ('embedding', 'Article Embedding')], max_length=20)),
                ('api_type', models.CharField(choices=[('chat', 'Chat Completion'), ('embedding', 'Embedding')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
