# Generated by Django 6.0.3 on 2026-03-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deep_dive', '0001_initial'),
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('digest', 'Digest Generation'), ('deep_dive', 'Deep Dive'), ('embedding', 'Article Embedding')], max_length=20)),
                ('api_type', models.CharField(choices=[('chat', 'Chat Completion'), ('embedding', 'Embedding')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deep_dive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to='deep_dive.deepdive')),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to='digest.digest')),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
