# Generated by Django 6.0.3 on 2026-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='step',
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='service',
            field=models.CharField(choices=[('summary', 'Article Summary')], max_length=20),
        ),
    ]
