# Generated by Django 6.0.3 on 2026-03-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='digest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to='digest.digest'),
        ),
    ]
