# Generated by Django 6.0.3 on 2026-03-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('digest', '0004_add_article_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to='digest.digestitem'),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='step',
            field=models.CharField(blank=True, choices=[('analyze', 'Analyze'), ('refine', 'Refine'), ('generate', 'Generate'), ('headline', 'Headline'), ('translate', 'Translate')], default='', max_length=20),
        ),
    ]
