# Generated by Django 6.0.3 on 2026-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_step_and_item_to_apiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='step',
            field=models.CharField(blank=True, choices=[('analyze', 'Analyze'), ('refine', 'Refine'), ('generate', 'Generate'), ('plan', 'Plan'), ('headline', 'Headline'), ('translate', 'Translate')], default='', max_length=20),
        ),
    ]
