# Generated by Django 6.0.3 on 2026-07-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_apiusage_step'),
        ('feed', '0011_articlesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to='feed.article'),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='service',
            field=models.CharField(choices=[('digest', 'Digest Generation'), ('research', 'Research'), ('summary', 'Article Summary'), ('embedding', 'Article Embedding')], max_length=20),
        ),
    ]
