# Generated by Django 6.0.3 on 2026-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_apiusage_article_alter_apiusage_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='research',
        ),
    ]
