# Generated by Django 6.0.3 on 2026-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
