# Generated by Django 6.0.3 on 2026-07-22 07:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('last_request_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('images_found', models.PositiveIntegerField(default=0)),
                ('images_downloaded', models.PositiveIntegerField(default=0)),
                ('images_skipped', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('article_id', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pipeline active')),
                ('max_workers', models.PositiveSmallIntegerField(default=2, help_text='Concurrent pipeline threads (1 = sequential, 2-6 = parallel). Lower = less CPU.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Max worker threads')),
                ('stage_delay', models.FloatField(default=0.5, help_text='Pause between pipeline ticks (0.05–60s). Higher = less CPU load.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(60.0)], verbose_name='Delay between tasks (sec)')),
                ('enable_feed_fetching', models.BooleanField(default=True, verbose_name='Feed fetching')),
                ('enable_content_extraction', models.BooleanField(default=True, verbose_name='Content extraction')),
                ('enable_topic_classification', models.BooleanField(default=True, verbose_name='Topic classification')),
                ('enable_embedding', models.BooleanField(default=True, verbose_name='Semantic embedding')),
                ('enable_section_assignment', models.BooleanField(default=True, verbose_name='Section assignment')),
                ('enable_image_download', models.BooleanField(default=True, verbose_name='Image download')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Settings',
                'verbose_name_plural': 'Pipeline Settings',
            },
        ),
        migrations.CreateModel(
            name='HarvesterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_extracted', models.PositiveIntegerField(default=0)),
                ('articles_failed', models.PositiveIntegerField(default=0)),
                ('articles_fallback', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='extract_runs', to='feed.article')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvesterFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('new_articles', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='fetch_runs', to='feed.article')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='feed.feed')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['feed', '-started_at'], name='harvester_h_feed_id_577b9a_idx')],
            },
        ),
    ]
