# Generated by Django 6.0.3 on 2026-03-25 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvesterEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_embedded', models.PositiveIntegerField(default=0)),
                ('chunks_created', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvesterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('images_found', models.PositiveIntegerField(default=0)),
                ('images_downloaded', models.PositiveIntegerField(default=0)),
                ('images_skipped', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvesterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('articles_found', models.PositiveIntegerField(default=0)),
                ('articles_extracted', models.PositiveIntegerField(default=0)),
                ('articles_failed', models.PositiveIntegerField(default=0)),
                ('articles_fallback', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='extract_runs', to='feed.article')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvesterFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('new_articles', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='fetch_runs', to='feed.article')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='feed.feed')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['feed', '-started_at'], name='harvester_h_feed_id_577b9a_idx')],
            },
        ),
    ]
