# Generated by Django 6.0.3 on 2026-07-22 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='section_score_floor',
            field=models.FloatField(default=0.5, help_text="Minimum cosine score between an article and a section's seed phrases for the article to be filed under that section.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Section match floor'),
        ),
    ]
