# Generated by Django 6.0.3 on 2026-03-25 21:44

from django.db import migrations, models


def seed_settings(apps, schema_editor):
    apps.get_model("harvester", "PipelineSettings").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_domainthrottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pipeline active')),
                ('enable_feed_fetching', models.BooleanField(default=True, verbose_name='Feed fetching')),
                ('enable_rss_image_download', models.BooleanField(default=True, verbose_name='RSS image download')),
                ('enable_content_extraction', models.BooleanField(default=True, verbose_name='Content extraction')),
                ('enable_og_image_download', models.BooleanField(default=True, verbose_name='OG image download')),
                ('enable_embedding', models.BooleanField(default=True, verbose_name='Embedding')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Settings',
                'verbose_name_plural': 'Pipeline Settings',
            },
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
