# Generated by Django 6.0.3 on 2026-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0003_pipelinesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at', 'stage'], name='harvester_p_started_d52eae_idx')],
            },
        ),
    ]
