# Generated by Django 6.0.3 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_pipeline_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipelineevent',
            name='harvester_p_started_d52eae_idx',
        ),
        migrations.AlterField(
            model_name='pipelineevent',
            name='stage',
            field=models.CharField(max_length=20),
        ),
    ]
