# Generated by Django 6.0.3 on 2026-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0005_simplify_pipeline_event_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineevent',
            name='article_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
