# Generated by Django 6.0.3 on 2026-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0006_add_article_id_to_pipeline_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='max_workers',
            field=models.PositiveSmallIntegerField(default=2, help_text='Concurrent pipeline threads (1 = sequential, 2-6 = parallel). Lower = less CPU.', verbose_name='Max worker threads'),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='stage_delay',
            field=models.FloatField(default=0.5, help_text='Pause between pipeline ticks. Higher = less CPU load.', verbose_name='Delay between tasks (sec)'),
        ),
    ]
