# Generated by Django 6.0.3 on 2026-04-08 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0007_add_max_workers_and_stage_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesettings',
            name='max_workers',
            field=models.PositiveSmallIntegerField(default=2, help_text='Concurrent pipeline threads (1 = sequential, 2-6 = parallel). Lower = less CPU.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Max worker threads'),
        ),
        migrations.AlterField(
            model_name='pipelinesettings',
            name='stage_delay',
            field=models.FloatField(default=0.5, help_text='Pause between pipeline ticks (0.05–60s). Higher = less CPU load.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(60.0)], verbose_name='Delay between tasks (sec)'),
        ),
    ]
