# Generated by Django 6.0.3 on 2026-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0008_alter_pipelinesettings_max_workers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarvesterEmbedding',
        ),
        migrations.RemoveField(
            model_name='pipelinesettings',
            name='enable_embedding',
        ),
        migrations.RemoveField(
            model_name='pipelinesettings',
            name='enable_og_image_download',
        ),
        migrations.RemoveField(
            model_name='pipelinesettings',
            name='enable_rss_image_download',
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='enable_image_download',
            field=models.BooleanField(default=True, verbose_name='Image download'),
        ),
    ]
