# Generated by Django 6.0.3 on 2026-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0009_delete_harvesterembedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='enable_topic_classification',
            field=models.BooleanField(default=True, verbose_name='Topic classification'),
        ),
    ]
