# Generated by Django 6.0.3 on 2026-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0010_pipelinesettings_enable_topic_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='enable_embedding',
            field=models.BooleanField(default=True, verbose_name='Semantic embedding'),
        ),
    ]
