# Generated by Django 6.0.3 on 2026-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0011_pipelinesettings_enable_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='enable_section_assignment',
            field=models.BooleanField(default=True, verbose_name='Section assignment'),
        ),
    ]
