# Generated by Django 6.0.3 on 2026-07-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this channel', max_length=200)),
                ('bot_token', models.CharField(blank=True, default='', help_text='Bot token override. Leave empty to use TELEGRAM_BOT_TOKEN from env', max_length=200)),
                ('chat_id', models.CharField(help_text='Channel ID (e.g. @mychannel or -1001234567890)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable posting to this channel')),
                ('top_n', models.PositiveIntegerField(default=10, help_text='Number of top news items to post (by freshness)')),
                ('post_time', models.TimeField(help_text='Time of day to post the digest (server timezone)')),
                ('include_images', models.BooleanField(default=True, help_text='Include article images in posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(help_text='Language for digest content posted to this channel', on_delete=django.db.models.deletion.CASCADE, to='core.language')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
    ]
