# Generated by Django 6.0.3 on 2026-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Bot token override. Leave empty to use TELEGRAM_BOT_TOKEN from env', max_length=200),
        ),
    ]
