# Generated by Django 6.0.3 on 2026-03-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0011_alter_digestconfig_items_per_section_max_and_more'),
        ('telegram', '0002_alter_telegramchannel_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_items', to='telegram.telegramchannel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sent', to='digest.digestitem')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('channel', 'item')},
            },
        ),
    ]
