# Generated by Django 6.0.3 on 2026-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_sentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='top_n',
            field=models.PositiveIntegerField(default=10, help_text='Number of top news items to post (by freshness)'),
        ),
    ]
