# Generated by Django 6.0.3 on 2026-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_telegramchannel_top_n'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegrampost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='digest',
        ),
        migrations.DeleteModel(
            name='SentItem',
        ),
        migrations.DeleteModel(
            name='TelegramPost',
        ),
    ]
