# Generated by Django 6.0.3 on 2026-03-24 10:00

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, default='', max_length=200)),
                ('name_uk', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(db_index=True, default='en', max_length=5)),
                ('headline', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DigestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='digest.digest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('importance', models.PositiveSmallIntegerField(default=0)),
                ('freshness', models.FloatField(db_index=True, default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='digest_items', to='feeds.article')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='feeds.articleimage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digest.digestsection')),
            ],
            options={
                'ordering': ['-freshness', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopicEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Search query describing this angle of the topic')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='digest.digesttopic')),
            ],
            options={
                'ordering': ['topic__order'],
            },
        ),
    ]
