# Generated by Django 6.0.3 on 2026-07-22 07:30

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_model', models.CharField(default='gpt-4.1-mini', help_text='Default OpenAI model (used by writer)', max_length=100)),
                ('planner_model', models.CharField(default='gpt-4.1', help_text='OpenAI model for the planner step (needs to produce many items, use full-size)', max_length=100)),
                ('temperature', models.FloatField(default=0.3, help_text='LLM temperature (0 = deterministic, 1 = creative)')),
                ('max_tokens_generation', models.PositiveIntegerField(default=4000, help_text='Max tokens for item generation response (includes all languages)')),
                ('hours_lookback', models.PositiveIntegerField(default=24, help_text='Collect articles published within this many hours')),
                ('embed_score_floor', models.FloatField(default=0.5, help_text="Minimum cosine score between an article and a section's embedding seeds for the article to be included in that section.")),
                ('edition_items_per_section', models.PositiveIntegerField(default=20, help_text='Target stories per section')),
                ('edition_max_workers', models.PositiveIntegerField(default=20, help_text='Max parallel writer threads')),
                ('edition_article_card_tokens', models.PositiveIntegerField(default=50, help_text='Max snippet length (tokens) per article in planner context')),
                ('edition_article_body_tokens', models.PositiveIntegerField(default=2000, help_text='Full content length (tokens) for writer per article')),
                ('edition_max_articles_per_story', models.PositiveIntegerField(default=5, help_text='Max articles sent to writer per story')),
                ('edition_writer_budget_tokens', models.PositiveIntegerField(default=6000, help_text='Hard cap on total article content tokens per write call')),
                ('edition_planner_budget_tokens', models.PositiveIntegerField(default=100000, help_text='Total token budget for planner context. Max articles is derived as budget // (article_card_tokens + overhead).')),
                ('system_prompt_planner', models.TextField(default='', help_text='Editor-in-chief prompt. Variables: {sections}, {items_per_section}, {section_count}, {total}')),
                ('system_prompt_writer', models.TextField(default='', help_text='Journalist prompt. Variables: {angle}, {languages}')),
            ],
            options={
                'verbose_name': 'Digest Configuration',
                'verbose_name_plural': 'Digest Configuration',
            },
        ),
        migrations.CreateModel(
            name='DigestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigestSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_translations', to='core.language')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='digest.digestsection')),
            ],
            options={
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SectionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='digest.digestsection')),
            ],
            options={
                'unique_together': {('section', 'text')},
            },
        ),
    ]
