# Generated by Django 6.0.3 on 2026-03-26 17:04

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_language_is_default'),
        ('feed', '0004_pipeline_split_images_add_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DigestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_model', models.CharField(default='gpt-4.1-mini', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens_analysis', models.PositiveIntegerField(default=2000)),
                ('max_tokens_generation', models.PositiveIntegerField(default=1500)),
                ('max_tokens_headline', models.PositiveIntegerField(default=1000)),
                ('max_tokens_translation', models.PositiveIntegerField(default=1000)),
                ('hours_lookback', models.PositiveIntegerField(default=36)),
                ('articles_per_section', models.PositiveIntegerField(default=25)),
                ('similarity_threshold', models.FloatField(default=0.25)),
                ('chunks_per_query', models.PositiveIntegerField(default=60)),
                ('article_snippet_length', models.PositiveIntegerField(default=300)),
                ('context_trim_length', models.PositiveIntegerField(default=1500)),
                ('refine_search_top_k', models.PositiveIntegerField(default=10)),
                ('items_per_section_min', models.PositiveIntegerField(default=4)),
                ('items_per_section_max', models.PositiveIntegerField(default=10)),
                ('max_workers', models.PositiveIntegerField(default=5)),
                ('system_prompt_analysis', models.TextField(default='You are a news analyst. Given articles from the "{section}" digest section, identify {min}-{max} distinct news stories.\n\nFor each story provide:\n- "label": brief story label (2-5 words, English)\n- "article_ids": array of article IDs covering this story\n- "search_queries": 2-3 search queries to find the most relevant articles about this specific story\n\nOutput ONLY valid JSON:\n{"stories": [{"label": "...", "article_ids": [...], "search_queries": ["...", "..."]}, ...]}')),
                ('system_prompt_generation', models.TextField(default='You are a world-class news analyst. Write a detailed news item about the following story based on the provided articles.\n\nProvide:\n- "topic": short event label (2-5 words)\n- "summary": what happened, context, why it matters (4-5 sentences)\n- "importance": integer 1-9 (1-3=minor, 4-5=notable, 6=significant, 7-9=major/breaking)\n- "article_ids": array of relevant article IDs from the input\n\nOutput ONLY valid JSON.')),
                ('system_prompt_headline', models.TextField(default='You are a news editor. Based on today\'s top stories, write a 2-3 sentence headline summarizing the overall news picture.\n\nOutput ONLY valid JSON: {"headline": "..."}')),
                ('system_prompt_translation', models.TextField(default='You are a professional translator. Translate the following news item from English to {language}.\nMaintain journalistic style, factual accuracy, and nuance. Adapt idioms and cultural references naturally. Do not add or remove information.\n\nProvide:\n- "topic": translated short event label\n- "summary": translated summary\n\nOutput ONLY valid JSON.')),
            ],
            options={
                'verbose_name': 'Digest Configuration',
                'verbose_name_plural': 'Digest Configuration',
            },
        ),
        migrations.CreateModel(
            name='DigestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('system_prompt_override', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('importance', models.PositiveSmallIntegerField(default=0)),
                ('freshness', models.FloatField(db_index=True, default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='digest_items', to='feed.article')),
                ('digest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digest.digest')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='feed.articleimage')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digest.digestsection')),
            ],
            options={
                'ordering': ['section__order', '-freshness', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SectionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Search query describing this angle of the section')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='digest.digestsection')),
            ],
            options={
                'ordering': ['section__order'],
            },
        ),
        migrations.CreateModel(
            name='DigestItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='digest.digestitem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_translations', to='core.language')),
            ],
            options={
                'unique_together': {('item', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DigestSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_translations', to='core.language')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='digest.digestsection')),
            ],
            options={
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DigestTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(blank=True, default='')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='digest.digest')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_translations', to='core.language')),
            ],
            options={
                'unique_together': {('digest', 'language')},
            },
        ),
    ]
