# Generated by Django 6.0.3 on 2026-03-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Analyzed'), (2, 'Refined'), (3, 'Generated'), (4, 'Saved'), (5, 'Done')], default=0),
        ),
        migrations.CreateModel(
            name='PipelineStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=200)),
                ('article_ids', models.JSONField(default=list)),
                ('search_queries', models.JSONField(default=list)),
                ('refined_articles', models.JSONField(default=list)),
                ('topic', models.CharField(default='', max_length=500)),
                ('summary', models.TextField(default='')),
                ('importance', models.PositiveSmallIntegerField(default=0)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stories', to='digest.digest')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digest.digestsection')),
            ],
            options={
                'ordering': ['section__order', '-importance'],
            },
        ),
    ]
