# Generated by Django 6.0.3 on 2026-07-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigestConfig',
        ),
    ]
