# Generated by Django 6.0.3 on 2026-03-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_add_stage_and_pipeline_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_label', models.CharField(default='', max_length=200)),
                ('article_ids', models.JSONField(default=list)),
                ('search_queries', models.JSONField(default=list)),
                ('refined_articles', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('refined_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='digest.digestitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PipelineStory',
        ),
    ]
