# Generated by Django 6.0.3 on 2026-03-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0003_replace_pipeline_story_with_item_pipeline'),
        ('feed', '0004_pipeline_split_images_add_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_uses', to='feed.article')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_uses', to='digest.digestitem')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='digest_arti_article_1ede85_idx')],
                'unique_together': {('article', 'item')},
            },
        ),
    ]
