# Generated by Django 6.0.3 on 2026-03-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_add_article_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='article_snippet_length',
            field=models.PositiveIntegerField(default=300, help_text='Snippet length (chars) sent to analyzer'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='articles_per_section',
            field=models.PositiveIntegerField(default=25, help_text='Max articles to collect per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='chat_model',
            field=models.CharField(default='gpt-4.1-mini', help_text='OpenAI model for analysis, generation, and translation', max_length=100),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='chunks_per_query',
            field=models.PositiveIntegerField(default=60, help_text='Max article chunks per embedding query'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='context_trim_length',
            field=models.PositiveIntegerField(default=1500, help_text='Article content length (chars) sent to generator'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='hours_lookback',
            field=models.PositiveIntegerField(default=36, help_text='Collect articles published within this many hours'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_max',
            field=models.PositiveIntegerField(default=10, help_text='Max stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_min',
            field=models.PositiveIntegerField(default=4, help_text='Min stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_analysis',
            field=models.PositiveIntegerField(default=2000, help_text='Max tokens for story analysis response'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_generation',
            field=models.PositiveIntegerField(default=1500, help_text='Max tokens for item generation response'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_headline',
            field=models.PositiveIntegerField(default=1000, help_text='Max tokens for headline generation response'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_translation',
            field=models.PositiveIntegerField(default=1000, help_text='Max tokens for translation response'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_workers',
            field=models.PositiveIntegerField(default=5, help_text='Max parallel workers (for batch mode)'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='refine_search_top_k',
            field=models.PositiveIntegerField(default=10, help_text='Additional articles to find per refine query'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='similarity_threshold',
            field=models.FloatField(default=0.25, help_text='Cosine distance threshold (0.25 = similarity >= 0.75)'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_analysis',
            field=models.TextField(default='You are a news analyst. Given articles from the "{section}" digest section, identify {min}-{max} distinct news stories.\n\nFor each story provide:\n- "label": brief story label (2-5 words, English)\n- "article_ids": array of article IDs covering this story\n- "search_queries": 2-3 search queries to find the most relevant articles about this specific story\n\nOutput ONLY valid JSON:\n{"stories": [{"label": "...", "article_ids": [...], "search_queries": ["...", "..."]}, ...]}', help_text='Prompt for identifying stories from articles. Variables: {section}, {min}, {max}'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_generation',
            field=models.TextField(default='You are a world-class news analyst. Write a detailed news item about the following story based on the provided articles.\n\nProvide:\n- "topic": short event label (2-5 words)\n- "summary": what happened, context, why it matters (4-5 sentences)\n- "importance": integer 1-9 (1-3=minor, 4-5=notable, 6=significant, 7-9=major/breaking)\n- "article_ids": array of relevant article IDs from the input\n\nOutput ONLY valid JSON.', help_text='Prompt for generating topic/summary/importance from articles'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_headline',
            field=models.TextField(default='You are a news editor. Based on today\'s top stories, write a 2-3 sentence headline summarizing the overall news picture.\n\nOutput ONLY valid JSON: {"headline": "..."}', help_text='Prompt for generating the overall digest headline'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_translation',
            field=models.TextField(default='You are a professional translator. Translate the following news item from English to {language}.\nMaintain journalistic style, factual accuracy, and nuance. Adapt idioms and cultural references naturally. Do not add or remove information.\n\nProvide:\n- "topic": translated short event label\n- "summary": translated summary\n\nOutput ONLY valid JSON.', help_text='Prompt for translating items. Variable: {language}'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='temperature',
            field=models.FloatField(default=0.3, help_text='LLM temperature (0 = deterministic, 1 = creative)'),
        ),
    ]
