# Generated by Django 6.0.3 on 2026-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0005_alter_digestconfig_article_snippet_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_analysis',
            field=models.TextField(default='You are a news analyst. Given articles from the "{section}" digest section, identify {min}-{max} distinct news stories.\n\nFor each story provide:\n- "label": brief story label (2-5 words, English)\n- "article_ids": array of article IDs covering this story\n- "search_queries": 2-3 search queries to find the most relevant articles about this specific story\n\nOutput ONLY valid JSON:\n{{"stories": [{{"label": "...", "article_ids": [...], "search_queries": ["...", "..."]}}, ...]}}', help_text='Prompt for identifying stories from articles. Variables: {section}, {min}, {max}'),
        ),
    ]
