# Generated by Django 6.0.3 on 2026-03-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0006_alter_digestconfig_system_prompt_analysis'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleuse',
            name='digest_arti_article_1ede85_idx',
        ),
    ]
