# Generated by Django 6.0.3 on 2026-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0007_remove_articleuse_digest_arti_article_1ede85_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='max_articles_per_story',
            field=models.PositiveIntegerField(default=7, help_text='Max articles sent to generator per story'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='context_trim_length',
            field=models.PositiveIntegerField(default=700, help_text='Article content length (chars) sent to generator'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_analysis',
            field=models.TextField(default='You are a news analyst. Given articles from the "{section}" digest section, identify {min}-{max} distinct news stories.\n\nFor each story provide:\n- "label": brief story label (2-5 words, English)\n- "article_ids": array of article IDs covering this story\n- "search_queries": 2-3 search queries to find the most relevant articles about this specific story\n\nReturn JSON with key "stories" containing an array of story objects.', help_text='Prompt for identifying stories from articles. Variables: {section}, {min}, {max}'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_generation',
            field=models.TextField(default='You are a world-class news analyst. Write a detailed news item about the following story based on the provided articles.\n\nProvide:\n- "topic": short event label (2-5 words)\n- "summary": what happened, context, why it matters (4-5 sentences)\n- "importance": integer 1-9 (1-3=minor, 4-5=notable, 6=significant, 7-9=major/breaking)\n- "article_ids": array of relevant article IDs from the input', help_text='Prompt for generating topic/summary/importance from articles'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_headline',
            field=models.TextField(default='You are a news editor. Based on today\'s top stories, write a 2-3 sentence headline summarizing the overall news picture.\n\nReturn JSON with a single key "headline".', help_text='Prompt for generating the overall digest headline'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_translation',
            field=models.TextField(default='You are a professional translator. Translate the following news item from English to {language}.\nMaintain journalistic style, factual accuracy, and nuance. Adapt idioms and cultural references naturally. Do not add or remove information.\n\nProvide:\n- "topic": translated short event label\n- "summary": translated summary', help_text='Prompt for translating items. Variable: {language}'),
        ),
    ]
