# Generated by Django 6.0.3 on 2026-03-28 22:06
# Config values are now managed by initdigest command, not migrations.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0008_digestconfig_max_articles_per_story_and_more'),
    ]

    operations = []
