# Generated by Django 6.0.3 on 2026-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0009_update_config_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_max',
            field=models.PositiveIntegerField(default=12, help_text='Max stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_min',
            field=models.PositiveIntegerField(default=10, help_text='Min stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_analysis',
            field=models.TextField(default='', help_text='Prompt for identifying stories from articles. Variables: {section}, {min}, {max}'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_generation',
            field=models.TextField(default='', help_text='Prompt for generating topic/summary/importance from articles'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_headline',
            field=models.TextField(default='', help_text='Prompt for generating the overall digest headline'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_translation',
            field=models.TextField(default='', help_text='Prompt for translating items. Variable: {language}'),
        ),
    ]
