# Generated by Django 6.0.3 on 2026-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0010_clean_prompt_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_max',
            field=models.PositiveIntegerField(default=8, help_text='Max stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_min',
            field=models.PositiveIntegerField(default=6, help_text='Min stories the analyzer should identify per section'),
        ),
    ]
