# Generated by Django 6.0.3 on 2026-04-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0011_alter_digestconfig_items_per_section_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestconfig',
            name='article_snippet_length',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='context_trim_length',
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='article_snippet_tokens',
            field=models.PositiveIntegerField(default=80, help_text='Snippet length (tokens) sent to analyzer per article'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='context_trim_tokens',
            field=models.PositiveIntegerField(default=250, help_text='Article content length (tokens) sent to generator per article (~1000 chars)'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_articles_per_story',
            field=models.PositiveIntegerField(default=3, help_text='Max articles sent to generator per story'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_generation',
            field=models.PositiveIntegerField(default=2500, help_text='Max tokens for item generation response (includes all languages)'),
        ),
    ]
