# Generated by Django 6.0.3 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0012_token_based_limits'),
        ('feed', '0006_articleimage_feed_articl_is_prim_9e6ea6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_max',
            field=models.PositiveIntegerField(default=20, help_text='Max stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_min',
            field=models.PositiveIntegerField(default=15, help_text='Min stories the analyzer should identify per section'),
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['stage', '-date'], name='digest_dige_stage_dd32d7_idx'),
        ),
        migrations.AddIndex(
            model_name='digestitem',
            index=models.Index(fields=['digest', '-freshness'], name='digest_dige_digest__eff638_idx'),
        ),
    ]
