# Generated by Django 6.0.3 on 2026-04-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0013_alter_digestconfig_items_per_section_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestconfig',
            name='max_tokens_headline',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='system_prompt_headline',
        ),
        migrations.RemoveField(
            model_name='digesttranslation',
            name='headline',
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='articles_per_section',
            field=models.PositiveIntegerField(default=20, help_text='Max articles to collect per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_max',
            field=models.PositiveIntegerField(default=15, help_text='Max stories the analyzer should identify per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='items_per_section_min',
            field=models.PositiveIntegerField(default=10, help_text='Min stories the analyzer should identify per section'),
        ),
    ]
