# Generated by Django 6.0.3 on 2026-04-05 16:20

import django.db.models.deletion
from django.db import migrations, models


def remove_duplicate_article_uses(apps, schema_editor):
    """Keep only the newest ArticleUse per article, delete the rest."""
    ArticleUse = apps.get_model("digest", "ArticleUse")
    from django.db.models import Max

    # Find articles with more than one use
    dupes = (
        ArticleUse.objects
        .values("article_id")
        .annotate(max_id=Max("id"))
        .filter(article_id__in=(
            ArticleUse.objects
            .values("article_id")
            .annotate(cnt=models.Count("id"))
            .filter(cnt__gt=1)
            .values("article_id")
        ))
    )
    keep_ids = set(d["max_id"] for d in dupes)

    if keep_ids:
        # Delete all rows for duplicate articles except the one we're keeping
        dupe_article_ids = set(d["article_id"] for d in dupes)
        deleted, _ = (
            ArticleUse.objects
            .filter(article_id__in=dupe_article_ids)
            .exclude(id__in=keep_ids)
            .delete()
        )
        print(f"\n  Removed {deleted} duplicate ArticleUse rows "
              f"({len(dupe_article_ids)} articles had duplicates)")


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0014_optimize_config_remove_headline'),
        ('feed', '0006_articleimage_feed_articl_is_prim_9e6ea6_idx'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_article_uses,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='articleuse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='articleuse',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_uses', to='feed.article'),
        ),
    ]
