# Generated by Django 6.0.3 on 2026-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0015_unique_article_in_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='hours_lookback',
            field=models.PositiveIntegerField(default=24, help_text='Collect articles published within this many hours'),
        ),
    ]
