# Generated by Django 6.0.3 on 2026-04-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0016_alter_digestconfig_hours_lookback'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='edition_article_body_tokens',
            field=models.PositiveIntegerField(default=2000, help_text='Full content length (tokens) for writer per article'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='edition_article_card_tokens',
            field=models.PositiveIntegerField(default=200, help_text='Snippet length (tokens) in planner context per article'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='edition_items_per_section',
            field=models.PositiveIntegerField(default=5, help_text='Target stories per section for Edition mode'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='edition_max_articles_per_story',
            field=models.PositiveIntegerField(default=5, help_text='Max articles sent to writer per story'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='edition_max_workers',
            field=models.PositiveIntegerField(default=20, help_text='Max parallel writer threads for Edition mode'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='system_prompt_planner',
            field=models.TextField(default='', help_text='Editor-in-chief prompt for Edition planner. Variables: {sections}, {items_per_section}'),
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='system_prompt_writer',
            field=models.TextField(default='', help_text='Journalist prompt for Edition writer. Variables: {angle}, {languages}'),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='articles_in_context',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='context_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='generation_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itempipeline',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DigestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('items_per_section', models.PositiveIntegerField(default=5)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('articles_collected', models.PositiveIntegerField(default=0)),
                ('stories_planned', models.PositiveIntegerField(default=0)),
                ('plan_duration_ms', models.PositiveIntegerField(default=0)),
                ('plan_input_tokens', models.PositiveIntegerField(default=0)),
                ('plan_output_tokens', models.PositiveIntegerField(default=0)),
                ('plan_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('items_generated', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('write_duration_ms', models.PositiveIntegerField(default=0)),
                ('write_input_tokens', models.PositiveIntegerField(default=0)),
                ('write_output_tokens', models.PositiveIntegerField(default=0)),
                ('write_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('digest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='digest.digest')),
            ],
            options={
                'verbose_name': 'Digest Run',
            },
        ),
    ]
