# Generated by Django 6.0.3 on 2026-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0017_digestconfig_edition_article_body_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='edition_writer_budget_tokens',
            field=models.PositiveIntegerField(default=6000, help_text='Hard cap on total article content tokens per write call'),
        ),
    ]
