# Generated by Django 6.0.3 on 2026-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0018_digestconfig_edition_writer_budget_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='edition_planner_budget_tokens',
            field=models.PositiveIntegerField(default=80000, help_text='Hard cap on total article card tokens sent to planner'),
        ),
    ]
