# Generated by Django 6.0.3 on 2026-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0019_digestconfig_edition_planner_budget_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_planner_budget_tokens',
            field=models.PositiveIntegerField(default=200000, help_text='Hard cap on total article card tokens sent to planner'),
        ),
    ]
