# Generated by Django 6.0.3 on 2026-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0020_alter_digestconfig_edition_planner_budget_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestconfig',
            name='article_snippet_tokens',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='articles_per_section',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='chunks_per_query',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='context_trim_tokens',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='items_per_section_max',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='items_per_section_min',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='max_articles_per_story',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='max_tokens_analysis',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='max_tokens_translation',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='max_workers',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='refine_search_top_k',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='system_prompt_analysis',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='system_prompt_generation',
        ),
        migrations.RemoveField(
            model_name='digestconfig',
            name='system_prompt_translation',
        ),
        migrations.RemoveField(
            model_name='digestsection',
            name='system_prompt_override',
        ),
        migrations.AlterField(
            model_name='digest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Pending'), (3, 'Generated'), (5, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='chat_model',
            field=models.CharField(default='gpt-4.1-mini', help_text='OpenAI model for generation', max_length=100),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_article_card_tokens',
            field=models.PositiveIntegerField(default=200, help_text='Max snippet length (tokens) per article in planner context'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_items_per_section',
            field=models.PositiveIntegerField(default=5, help_text='Target stories per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_max_workers',
            field=models.PositiveIntegerField(default=20, help_text='Max parallel writer threads'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_planner',
            field=models.TextField(default='', help_text='Editor-in-chief prompt. Variables: {sections}, {items_per_section}'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_writer',
            field=models.TextField(default='', help_text='Journalist prompt. Variables: {angle}, {languages}'),
        ),
        migrations.DeleteModel(
            name='SectionEmbedding',
        ),
    ]
