# Generated by Django 6.0.3 on 2026-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0021_remove_digestconfig_article_snippet_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='edition_max_planner_articles',
            field=models.PositiveIntegerField(default=2000, help_text='Max articles sent to planner (round-robin picks from all feeds)'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_planner_budget_tokens',
            field=models.PositiveIntegerField(default=80000, help_text='Hard cap on total article card tokens sent to planner'),
        ),
    ]
