# Generated by Django 6.0.3 on 2026-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0022_digestconfig_edition_max_planner_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='max_tokens_generation',
            field=models.PositiveIntegerField(default=4000, help_text='Max tokens for item generation response (includes all languages)'),
        ),
    ]
