# Generated by Django 6.0.3 on 2026-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0023_alter_digestconfig_max_tokens_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Pending'), (5, 'Done')], default=0),
        ),
    ]
