# Generated by Django 6.0.3 on 2026-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0024_alter_digest_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_planner',
            field=models.TextField(default='', help_text='Editor-in-chief prompt. Variables: {sections}, {items_per_section}, {total}'),
        ),
    ]
