# Generated by Django 6.0.3 on 2026-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0025_alter_digestconfig_system_prompt_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestconfig',
            name='planner_model',
            field=models.CharField(default='gpt-4.1', help_text='OpenAI model for the planner step (needs to produce many items, use full-size)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='chat_model',
            field=models.CharField(default='gpt-4.1-mini', help_text='Default OpenAI model (used by writer)', max_length=100),
        ),
    ]
