# Generated by Django 6.0.3 on 2026-04-16 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0026_digestconfig_planner_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestitem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='digest.digestsection'),
        ),
    ]
