# Generated by Django 6.0.3 on 2026-04-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0027_protect_section_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestitem',
            name='importance',
        ),
    ]
