# Generated by Django 6.0.3 on 2026-04-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0028_remove_digestitem_importance'),
        ('feed', '0008_remove_rss_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestitem',
            name='image',
        ),
        migrations.AddField(
            model_name='digestitem',
            name='cover_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_covers', to='feed.article'),
        ),
    ]
