# Generated by Django 6.0.3 on 2026-04-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0029_remove_digestitem_image_digestitem_cover_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleUse',
        ),
    ]
