# Generated by Django 6.0.3 on 2026-04-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0030_delete_articleuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestitem',
            name='cover_article',
        ),
    ]
