# Generated by Django 6.0.3 on 2026-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0031_remove_digestitem_cover_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_article_card_tokens',
            field=models.PositiveIntegerField(default=50, help_text='Max snippet length (tokens) per article in planner context'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_items_per_section',
            field=models.PositiveIntegerField(default=10, help_text='Target stories per section'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_max_planner_articles',
            field=models.PositiveIntegerField(default=1333, help_text='Max articles sent to planner (round-robin picks from all feeds)'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_planner_budget_tokens',
            field=models.PositiveIntegerField(default=100000, help_text='Hard cap on total article card tokens sent to planner'),
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='system_prompt_planner',
            field=models.TextField(default='', help_text='Editor-in-chief prompt. Variables: {sections}, {items_per_section}, {section_count}, {total}'),
        ),
    ]
