# Generated by Django 6.0.3 on 2026-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0032_alter_digestconfig_edition_article_card_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digestconfig',
            name='edition_max_planner_articles',
        ),
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_planner_budget_tokens',
            field=models.PositiveIntegerField(default=100000, help_text='Total token budget for planner context. Max articles is derived as budget // (article_card_tokens + overhead).'),
        ),
    ]
