# Generated by Django 6.0.3 on 2026-07-21 09:05

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0033_remove_digestconfig_edition_max_planner_articles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digestitem',
            options={'ordering': ['section__order', '-match_score', '-freshness', 'order']},
        ),
        migrations.AddField(
            model_name='digestconfig',
            name='embed_score_floor',
            field=models.FloatField(default=0.5, help_text="Minimum cosine score between an article and a section's embedding seeds for the article to be included in that section."),
        ),
        migrations.AddField(
            model_name='digestitem',
            name='match_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='SectionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='digest.digestsection')),
            ],
            options={
                'unique_together': {('section', 'text')},
            },
        ),
    ]
