# Generated by Django 6.0.3 on 2026-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0034_alter_digestitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestconfig',
            name='edition_items_per_section',
            field=models.PositiveIntegerField(default=20, help_text='Target stories per section'),
        ),
    ]
