# Generated by Django 6.0.3 on 2026-07-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0035_alter_digestconfig_edition_items_per_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digestitem',
            options={'ordering': ['section__order', '-freshness', '-id']},
        ),
    ]
