# Generated by Django 6.0.3 on 2026-07-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0036_alter_digestitem_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digestitemtranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='digesttranslation',
            unique_together=set(),
        ),
    ]
