# Generated by Django 6.0.3 on 2026-07-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0037_drop_translation_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='digest',
            name='digest_dige_stage_dd32d7_idx',
        ),
        migrations.RemoveField(
            model_name='digestrun',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='digesttranslation',
            name='digest',
        ),
        migrations.RemoveIndex(
            model_name='digestitem',
            name='digest_dige_digest__eff638_idx',
        ),
        migrations.RemoveField(
            model_name='itempipeline',
            name='item',
        ),
        migrations.RemoveField(
            model_name='digestitemtranslation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='digestitemtranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='digesttranslation',
            name='language',
        ),
        migrations.DeleteModel(
            name='DigestRun',
        ),
        migrations.RemoveField(
            model_name='digestitem',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='digestitem',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='digestitem',
            name='section',
        ),
        migrations.DeleteModel(
            name='ItemPipeline',
        ),
        migrations.DeleteModel(
            name='DigestItemTranslation',
        ),
        migrations.DeleteModel(
            name='DigestTranslation',
        ),
        migrations.DeleteModel(
            name='Digest',
        ),
        migrations.DeleteModel(
            name='DigestItem',
        ),
    ]
