# Generated by Django 4.2.29 on 2026-03-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0008_add_rss_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('view_name', models.CharField(blank=True, default='', max_length=100)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('session_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('is_bot', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('os', models.CharField(blank=True, default='', max_length=50)),
                ('referrer', models.URLField(blank=True, default='', max_length=2000)),
                ('referrer_domain', models.CharField(blank=True, default='', max_length=253)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='news.article')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='news.category')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'is_bot'], name='analytics_p_timesta_2e2989_idx'), models.Index(fields=['view_name', 'timestamp'], name='analytics_p_view_na_097a00_idx'), models.Index(fields=['article', 'timestamp'], name='analytics_p_article_f40bd7_idx'), models.Index(fields=['referrer_domain', 'timestamp'], name='analytics_p_referre_e618ab_idx'), models.Index(fields=['country', 'timestamp'], name='analytics_p_country_7b28c5_idx')],
            },
        ),
    ]
