# Generated by Django 6.0.3 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_client_latitude_client_longitude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='analytics_s_is_huma_f2ba36_idx',
        ),
        migrations.AddField(
            model_name='session',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pages',
            field=models.JSONField(blank=True, default=list, help_text='[{"path": "/...", "ts": "HH:MM:SS"}]'),
        ),
        migrations.AddField(
            model_name='session',
            name='spm',
            field=models.FloatField(default=0, help_text='Scrolls per minute'),
        ),
        migrations.AddField(
            model_name='session',
            name='total_scrolls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='session',
            name='has_interaction',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_human',
        ),
    ]
