# Generated by Django 6.0.3 on 2026-03-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_client_session_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_session_33d90e_idx',
            old_name='analytics_a_session_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_type_2ad86c_idx',
            old_name='analytics_a_type_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_article_223700_idx',
            old_name='analytics_a_article_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_path_2cb692_idx',
            old_name='analytics_a_path_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='analytics_c_last_se_83d249_idx',
            old_name='analytics_c_last_se_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='analytics_c_is_bot_bc7b3b_idx',
            old_name='analytics_c_is_bot_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='analytics_c_country_c11da9_idx',
            old_name='analytics_c_country_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_started_783082_idx',
            old_name='analytics_s_started_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_client__3bcd7f_idx',
            old_name='analytics_s_client_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='analytics_s_is_huma_f2ba36_idx',
            old_name='analytics_s_is_huma_idx',
        ),
    ]
