# Generated by Django 6.0.3 on 2026-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_session_analytics_s_is_huma_f2ba36_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
