# Generated by Django 6.0.3 on 2026-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_analytics_a_session_idx_analytics_a_session_33d90e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bot_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='source',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('http', 'HTTP')], default='websocket', max_length=10),
        ),
    ]
