# Generated by Django 6.0.3 on 2026-04-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ip_hash',
        ),
    ]
