"""Default digest sections with translations and embedding descriptions.

Used by the initdigest management command to seed the database.
Each section has ~20 embedding descriptions for broad news coverage.
"""

SECTIONS = [
    {
        "slug": "ai-technology",
        "order": 0,
        "description": "Artificial intelligence, big tech, gadgets, software, digital innovation",
        "translations": {
            "en": "AI & Technology",
            "ru": "AI • Технологии",
            "uk": "AI • Технології",
        },
        "embeddings": [
            "Artificial intelligence breakthroughs, new AI models, and machine learning advances",
            "Big tech companies: Apple, Google, Microsoft, Meta, Amazon news and strategy",
            "Semiconductor industry, chip manufacturing, and tech supply chains",
            "Social media platforms, content moderation, and digital regulation",
            "Space technology, satellite launches, and commercial space industry",
            "Tech startup funding, venture capital, and unicorn company valuations",
            "Robotics advances, automation technology, and industrial innovation",
            "AI regulation, ethics debates, and government tech policy",
            "Cloud computing, enterprise software, and digital transformation news",
            "Consumer electronics, gadgets, smartphones, and hardware launches",
            "Generative AI applications, ChatGPT competitors, and AI-powered products",
            "Autonomous vehicles, self-driving technology, and transportation AI",
            "Quantum computing research, quantum supremacy, and quantum hardware",
            "Wearable technology, AR/VR headsets, and mixed reality devices",
            "Telecom industry, 5G/6G networks, and wireless connectivity advances",
            "Computer vision, image recognition, and AI in visual media",
            "Natural language processing, voice assistants, and conversational AI",
            "Data centers, AI infrastructure, and GPU shortage news",
            "Tech layoffs, hiring trends, and talent competition in the tech industry",
            "Open-source AI models, model weights releases, and AI democratization",
        ],
    },
    {
        "slug": "world-politics",
        "order": 1,
        "description": "International relations, diplomacy, geopolitics, summits, treaties, sanctions",
        "translations": {
            "en": "World Politics",
            "ru": "Мировая политика",
            "uk": "Світова політика",
        },
        "embeddings": [
            "International diplomacy and foreign policy negotiations between world leaders",
            "United Nations resolutions, votes, and multilateral agreements",
            "NATO alliance decisions, military cooperation, and defense pacts",
            "Geopolitical tensions and rivalry between major world powers",
            "Economic sanctions, trade embargoes, and diplomatic pressure campaigns",
            "Presidential and prime ministerial summits and bilateral meetings",
            "International treaties, accords, and diplomatic breakthroughs",
            "Global governance reform and international institution changes",
            "Diplomatic crises, ambassador recalls, and embassy incidents",
            "Elections, referendums, and political transitions around the world",
            "G7 and G20 summit outcomes, joint statements, and policy coordination",
            "EU politics, European Parliament decisions, and Brussels policy debates",
            "Middle East geopolitics, Israel-Palestine diplomacy, and Gulf state relations",
            "Asia-Pacific geopolitics, ASEAN summits, and Indo-Pacific strategy",
            "Africa politics, African Union decisions, and regional power dynamics",
            "Latin America politics, elections, and regional cooperation efforts",
            "Political scandals, impeachment proceedings, and corruption investigations",
            "Arms control negotiations, non-proliferation talks, and weapons treaties",
            "Intelligence alliances, Five Eyes cooperation, and spy agency revelations",
            "Government formation, coalition politics, and parliamentary crises",
        ],
    },
    {
        "slug": "business-economy",
        "order": 2,
        "description": "Global economy, stock markets, central banks, trade, inflation, corporations",
        "translations": {
            "en": "Business & Economy",
            "ru": "Бизнес • Экономика",
            "uk": "Бізнес • Економіка",
        },
        "embeddings": [
            "Stock market movements, Wall Street trading, and major index changes",
            "Central bank interest rate decisions, Federal Reserve, and ECB policy",
            "Global inflation data, consumer prices, and cost of living trends",
            "International trade agreements, tariffs, and supply chain disruptions",
            "Major corporate earnings, mergers, acquisitions, and business deals",
            "Oil and energy prices, OPEC decisions, and commodity markets",
            "Employment data, unemployment rates, and labor market trends",
            "Global economic forecasts, GDP growth, and recession indicators",
            "Banking sector news, financial regulation, and fintech developments",
            "Real estate markets, housing prices, and commercial property trends",
            "Sovereign debt crises, government bonds, and national credit ratings",
            "Retail industry trends, consumer spending, and e-commerce growth",
            "Private equity deals, leveraged buyouts, and hedge fund strategies",
            "IPO launches, SPAC deals, and companies going public or private",
            "Currency exchange rate volatility, dollar strength, and forex markets",
            "Bankruptcy filings, corporate restructuring, and debt default events",
            "Agriculture commodities, food prices, and global supply shortages",
            "Wealth inequality, billionaire rankings, and CEO compensation debates",
            "Insurance industry, reinsurance markets, and catastrophe losses",
            "Startup ecosystem, tech valuations, and Series A-D funding rounds",
        ],
    },
    {
        "slug": "crypto-fintech",
        "order": 3,
        "description": "Cryptocurrency, blockchain, DeFi, digital payments, fintech startups",
        "translations": {
            "en": "Crypto & Fintech",
            "ru": "Крипто • Финтех",
            "uk": "Крипто • Фінтех",
        },
        "embeddings": [
            "Bitcoin price movements, halving events, and market dominance shifts",
            "Ethereum ecosystem, smart contracts, and layer-2 scaling solutions",
            "Cryptocurrency regulation, SEC enforcement, and global policy frameworks",
            "DeFi protocols, yield farming, liquidity pools, and decentralized exchanges",
            "NFT market trends, digital collectibles, and tokenization of assets",
            "Stablecoin developments, CBDC launches, and digital currency policy",
            "Crypto exchange news, Binance, Coinbase, and trading platform updates",
            "Blockchain technology adoption by enterprises and governments",
            "Fintech startups, digital banking, mobile payments, and neobanks",
            "Web3 development, DAOs, and decentralized governance experiments",
            "Crypto mining, proof-of-work energy debates, and mining hardware",
            "Cross-border payments, remittance solutions, and payment networks",
            "Crypto whale movements, large transactions, and market manipulation",
            "Solana, Cardano, Polkadot, and alternative Layer-1 blockchain news",
            "Real-world asset tokenization, security tokens, and regulated exchanges",
            "Crypto hacks, exchange breaches, and stolen funds recovery",
            "Buy-now-pay-later services, embedded finance, and lending platforms",
            "Meme coins, social trading, and retail crypto speculation trends",
            "Institutional crypto adoption, Bitcoin ETFs, and Wall Street involvement",
            "Decentralized identity, digital wallets, and self-sovereign identity",
        ],
    },
    {
        "slug": "war-conflicts",
        "order": 4,
        "description": "Wars, military operations, armed conflicts, defense, security threats",
        "translations": {
            "en": "War & Conflicts",
            "ru": "Война • Конфликты",
            "uk": "Війна • Конфлікти",
        },
        "embeddings": [
            "Armed conflicts, wars, and military operations around the world",
            "Ceasefire violations, truce collapses, and escalation of hostilities",
            "Military weapons systems, defense technology, and arms deals",
            "Refugee crises and humanitarian disasters caused by conflict",
            "Nuclear weapons proliferation and disarmament negotiations",
            "Peacekeeping missions and international military interventions",
            "Intelligence operations, espionage scandals, and security breaches",
            "Civil unrest, coups, and political violence in unstable regions",
            "Defense budgets, military spending, and army modernization programs",
            "Peace negotiations, ceasefire agreements, and conflict resolution talks",
            "Drone warfare, UAV strikes, and unmanned military technology",
            "Naval confrontations, maritime disputes, and sea lane security",
            "Mercenary groups, private military contractors, and proxy wars",
            "War crimes documentation, evidence gathering, and accountability",
            "Military alliances, joint exercises, and coalition operations",
            "Guerrilla warfare, insurgency, and counter-insurgency campaigns",
            "Humanitarian aid corridors, supply blockades, and siege conditions",
            "Veteran affairs, PTSD research, and post-conflict rehabilitation",
            "Missile defense systems, air defense, and ballistic missile tests",
            "Cyber warfare, electronic warfare, and information operations in conflict",
        ],
    },
    {
        "slug": "disasters-emergencies",
        "order": 5,
        "description": "Natural disasters, accidents, emergencies, catastrophes, rescue operations",
        "translations": {
            "en": "Disasters & Emergencies",
            "ru": "Катастрофы • ЧП",
            "uk": "Катастрофи • НС",
        },
        "embeddings": [
            "Earthquakes, tsunamis, and seismic activity causing destruction",
            "Hurricanes, typhoons, cyclones, and severe storm damage",
            "Wildfires, forest fires, and large-scale fire emergencies",
            "Flooding, landslides, and water-related natural disasters",
            "Aviation accidents, plane crashes, and air safety incidents",
            "Industrial accidents, factory explosions, and chemical spills",
            "Train derailments, maritime disasters, and transportation accidents",
            "Volcanic eruptions, geological hazards, and evacuation orders",
            "Rescue operations, emergency response, and disaster relief efforts",
            "Infrastructure collapses, building failures, and bridge accidents",
            "Drought, water crisis, and extreme heat wave emergencies",
            "Nuclear and radiological incidents, reactor emergencies, and contamination",
            "Mine collapses, mining accidents, and underground rescue operations",
            "Mass casualty events, crowd crush incidents, and festival disasters",
            "Oil spills, tanker accidents, and marine pollution emergencies",
            "Space debris, satellite reentry, and orbital hazard incidents",
            "Power grid failures, blackouts, and energy infrastructure emergencies",
            "Pandemic outbreaks, quarantine zones, and emergency health declarations",
            "Dam failures, reservoir breaches, and flood control system failures",
            "Tornado outbreaks, hail storms, and severe convective weather events",
        ],
    },
    {
        "slug": "science",
        "order": 6,
        "description": "Scientific research, space exploration, physics, biology, discoveries",
        "translations": {
            "en": "Science",
            "ru": "Наука",
            "uk": "Наука",
        },
        "embeddings": [
            "Space exploration missions, NASA discoveries, and Mars exploration",
            "Physics discoveries, quantum computing, and fundamental science",
            "Astronomy discoveries, telescope observations, and cosmic phenomena",
            "Climate science research, environmental studies, and ecological findings",
            "Genetics research, gene therapy, and CRISPR technology advances",
            "Biology breakthroughs, evolution research, and species discoveries",
            "Chemistry and materials science advances and new compounds",
            "Ocean exploration, deep sea discoveries, and marine science",
            "Archaeology discoveries, paleontology findings, and historical research",
            "Nobel Prize announcements, major scientific awards, and research funding",
            "Neuroscience breakthroughs, brain research, and cognitive science",
            "Earth science, geology, and plate tectonics research findings",
            "Fusion energy research, tokamak experiments, and clean energy physics",
            "Exoplanet discoveries, habitability studies, and astrobiology research",
            "Artificial life, synthetic biology, and bioengineering advances",
            "Nanotechnology applications, molecular machines, and nanomedicine",
            "Mathematical breakthroughs, proof discoveries, and computational math",
            "Particle physics, CERN experiments, and collider discoveries",
            "Conservation biology, endangered species research, and wildlife studies",
            "Science policy, research ethics, and academic integrity controversies",
        ],
    },
    {
        "slug": "health-medicine",
        "order": 7,
        "description": "Medical breakthroughs, epidemics, public health, pharmaceuticals, mental health",
        "translations": {
            "en": "Health & Medicine",
            "ru": "Здоровье • Медицина",
            "uk": "Здоров'я • Медицина",
        },
        "embeddings": [
            "Medical research breakthroughs, new treatments, and drug approvals",
            "Pandemic monitoring, infectious disease outbreaks, and WHO alerts",
            "Vaccine development, clinical trials, and immunization campaigns",
            "Mental health research, psychology studies, and public health policy",
            "Cancer research, oncology breakthroughs, and treatment innovations",
            "Pharmaceutical industry news, drug pricing, and patent disputes",
            "Public health crises, healthcare system challenges, and hospital capacity",
            "Nutrition research, diet studies, and food safety regulations",
            "Organ transplant advances, surgical innovations, and medical devices",
            "Healthcare policy, insurance reform, and universal coverage debates",
            "Antibiotic resistance, superbugs, and antimicrobial research",
            "Rare diseases research, orphan drugs, and genetic disorder treatments",
            "Telemedicine, digital health platforms, and remote patient monitoring",
            "Aging research, longevity science, and geriatric care innovations",
            "Biotech company news, IPOs, and biotech industry developments",
            "Addiction treatment, opioid crisis, and substance abuse research",
            "Global health initiatives, WHO programs, and disease eradication campaigns",
            "Reproductive health, fertility research, and maternal care advances",
            "Wearable health devices, biosensors, and personal health tracking",
            "Medical AI, diagnostic algorithms, and AI-assisted surgery systems",
        ],
    },
    {
        "slug": "crime-justice",
        "order": 8,
        "description": "Crime, law enforcement, court rulings, investigations, legal proceedings",
        "translations": {
            "en": "Crime & Justice",
            "ru": "Криминал • Правосудие",
            "uk": "Кримінал • Правосуддя",
        },
        "embeddings": [
            "Major criminal investigations, high-profile arrests, and manhunts",
            "Court rulings, landmark legal decisions, and Supreme Court cases",
            "Organized crime, drug trafficking, and cartel operations",
            "White-collar crime, fraud schemes, and financial scandals",
            "Police reform, law enforcement controversies, and use-of-force incidents",
            "Prison system news, incarceration rates, and criminal justice reform",
            "Terrorism investigations, extremist arrests, and counter-terrorism",
            "International criminal tribunals, war crimes trials, and extraditions",
            "Mass shootings, gun violence, and firearms legislation debates",
            "Human trafficking, smuggling networks, and cross-border crime",
            "Corporate lawsuits, class action settlements, and antitrust cases",
            "Wrongful convictions, exonerations, and innocence project cases",
            "Cybercrime prosecutions, online fraud, and digital evidence cases",
            "Political corruption trials, bribery charges, and official misconduct",
            "Juvenile justice, youth crime, and rehabilitation programs",
            "Domestic violence legislation, stalking laws, and victim protection",
            "Money laundering, sanctions evasion, and financial crime enforcement",
            "Death penalty debates, executions, and capital punishment policy",
            "Whistleblower cases, leaked documents, and protection legislation",
            "Environmental crimes, illegal dumping, and wildlife poaching prosecution",
        ],
    },
    {
        "slug": "cybersecurity-privacy",
        "order": 9,
        "description": "Cybersecurity, data breaches, hacking, privacy, surveillance, digital rights",
        "translations": {
            "en": "Cybersecurity & Privacy",
            "ru": "Кибербезопасность • Приватность",
            "uk": "Кібербезпека • Приватність",
        },
        "embeddings": [
            "Major data breaches, leaked databases, and personal information exposure",
            "Ransomware attacks on corporations, hospitals, and government agencies",
            "State-sponsored hacking, cyber espionage, and nation-state cyber operations",
            "Zero-day vulnerabilities, software exploits, and security patches",
            "Privacy legislation, GDPR enforcement, and data protection regulations",
            "Surveillance technology, facial recognition, and government monitoring",
            "Phishing campaigns, social engineering, and online scam operations",
            "Critical infrastructure cyberattacks on power grids and water systems",
            "Encryption debates, backdoor mandates, and digital rights activism",
            "Dark web marketplaces, cybercrime forums, and law enforcement takedowns",
            "Supply chain attacks, compromised software updates, and third-party risk",
            "Bug bounty programs, responsible disclosure, and security researcher news",
            "IoT security vulnerabilities, smart device hacking, and connected car risks",
            "AI-powered cyberattacks, deepfake threats, and AI-generated phishing",
            "Cloud security breaches, misconfigured services, and data exposure",
            "Election security, voting system vulnerabilities, and disinformation campaigns",
            "Insider threats, employee data theft, and corporate espionage cases",
            "Cyber insurance market, breach costs, and incident response industry",
            "Children's online safety, age verification, and social media protection",
            "Spyware industry, Pegasus-like tools, and commercial surveillance vendors",
        ],
    },
    {
        "slug": "energy-climate",
        "order": 10,
        "description": "Energy policy, renewable energy, climate change, environmental regulation",
        "translations": {
            "en": "Energy & Climate",
            "ru": "Энергетика • Климат",
            "uk": "Енергетика • Клімат",
        },
        "embeddings": [
            "Climate change policy, COP summits, and emission reduction commitments",
            "Renewable energy expansion, solar and wind power projects",
            "Oil and gas industry developments, drilling, and pipeline projects",
            "Nuclear energy policy, reactor construction, and atomic regulation",
            "Carbon capture technology, green hydrogen, and clean energy innovation",
            "Electric vehicles, EV charging infrastructure, and battery technology",
            "Environmental regulation, pollution control, and industrial emissions",
            "Extreme weather events linked to climate change and adaptation measures",
            "Energy security, supply crises, and geopolitical energy competition",
            "Deforestation, ocean pollution, biodiversity loss, and conservation efforts",
            "Green finance, ESG investing, carbon credits, and climate-related bonds",
            "Water scarcity, desalination technology, and freshwater resource management",
            "Sustainable agriculture, regenerative farming, and food system emissions",
            "Arctic and Antarctic ice loss, permafrost thaw, and polar research",
            "Offshore wind farms, tidal energy, and marine renewable energy projects",
            "Plastic pollution, recycling technology, and waste management innovation",
            "Urban sustainability, green buildings, and smart city energy solutions",
            "Methane emissions regulation, gas flaring, and fugitive emission tracking",
            "Energy storage, grid-scale batteries, and power grid modernization",
            "Climate litigation, lawsuits against fossil fuel companies, and legal action",
        ],
    },
    {
        "slug": "sports",
        "order": 11,
        "description": "Major sports leagues, Olympics, championships, transfers, records",
        "translations": {
            "en": "Sports",
            "ru": "Спорт",
            "uk": "Спорт",
        },
        "embeddings": [
            "Football (soccer) league results, Champions League, and World Cup news",
            "American sports: NFL, NBA, MLB, NHL scores and championship updates",
            "Olympic Games preparation, competition results, and medal standings",
            "Tennis Grand Slam tournaments, rankings, and major match results",
            "Formula 1 racing, MotoGP, and motorsport championship standings",
            "Transfer market news, player signings, and contract negotiations",
            "Sports doping scandals, anti-doping investigations, and athlete bans",
            "Boxing and MMA: major fights, title bouts, and combat sports news",
            "Cricket, rugby, and other international sports tournament results",
            "Sports business, broadcasting rights, stadium deals, and franchise values",
            "Golf majors, PGA Tour, and professional golf tournament results",
            "Athletics, track and field records, and world championship results",
            "Winter sports: skiing, ice hockey, and figure skating competitions",
            "Cycling, Tour de France, Giro d'Italia, and professional cycling news",
            "Swimming, diving, and aquatic sports world records and championships",
            "College sports, NCAA tournaments, and student athlete news",
            "Esports tournaments, competitive gaming, and professional gaming leagues",
            "Sports injuries, athlete rehabilitation, and sports medicine advances",
            "FIFA and IOC governance, sports organization corruption, and reform",
            "Extreme sports, adventure racing, and action sports competitions",
        ],
    },
    {
        "slug": "entertainment-culture",
        "order": 12,
        "description": "Movies, music, TV, celebrities, art, cultural events, media",
        "translations": {
            "en": "Entertainment & Culture",
            "ru": "Развлечения • Культура",
            "uk": "Розваги • Культура",
        },
        "embeddings": [
            "Movie releases, box office results, and film festival awards",
            "Music industry news, album releases, concerts, and chart rankings",
            "Television series premieres, streaming platform content, and ratings",
            "Celebrity news, scandals, and entertainment industry events",
            "Art exhibitions, museum openings, and visual arts events",
            "Book releases, literary awards, and publishing industry news",
            "Theater, Broadway, and performing arts events and reviews",
            "Video game releases, gaming industry, and esports tournaments",
            "Awards ceremonies: Oscars, Grammys, Emmys, and Golden Globes",
            "Streaming wars, content deals, and entertainment business mergers",
            "K-pop, J-pop, and Asian entertainment global cultural impact",
            "Podcast industry, audio content, and creator economy trends",
            "Fashion industry, luxury brands, and major fashion week events",
            "Comedy specials, stand-up tours, and comedians in the news",
            "Documentary releases, true crime content, and investigative media",
            "Music festivals, live concert tours, and venue industry news",
            "Anime, manga releases, and Japanese animation industry trends",
            "Celebrity philanthropy, charity events, and cultural fundraisers",
            "Social media influencers, content creators, and viral cultural moments",
            "Heritage preservation, cultural landmarks, and UNESCO world heritage news",
        ],
    },
    {
        "slug": "dev-opensource",
        "order": 13,
        "description": "Software development, open source projects, programming, developer tools",
        "translations": {
            "en": "Development & Open Source",
            "ru": "Разработка • Open Source",
            "uk": "Розробка • Open Source",
        },
        "embeddings": [
            "Open source project releases, major version updates, and community news",
            "Programming language updates, new features, and ecosystem developments",
            "Developer tools, IDEs, code editors, and productivity software",
            "GitHub trending projects, repository milestones, and community events",
            "Linux kernel development, distribution releases, and system administration",
            "Web development frameworks, frontend and backend technology trends",
            "DevOps practices, CI/CD pipelines, and infrastructure as code",
            "API design, microservices architecture, and software engineering practices",
            "Tech conferences, developer events, and hackathon results",
            "Database technology, data engineering, and distributed systems advances",
            "Rust, Go, Zig, and systems programming language ecosystem news",
            "JavaScript/TypeScript ecosystem, npm packages, and Node.js updates",
            "Python ecosystem, PyPI packages, machine learning libraries, and frameworks",
            "Kubernetes, Docker, containers, and cloud-native orchestration tools",
            "WebAssembly, edge computing, and serverless platform developments",
            "Code security, dependency vulnerabilities, and software supply chain safety",
            "AI coding assistants, Copilot alternatives, and AI-powered development tools",
            "Mobile app development, iOS and Android SDK updates, and cross-platform tools",
            "Open source licensing disputes, governance issues, and community conflicts",
            "Observability, logging, monitoring, and distributed tracing tools",
        ],
    },
    {
        "slug": "society-migration",
        "order": 14,
        "description": "Social movements, migration, demographics, education, human rights",
        "translations": {
            "en": "Society & Migration",
            "ru": "Общество • Миграция",
            "uk": "Суспільство • Міграція",
        },
        "embeddings": [
            "Immigration policy, visa regulations, and border control measures",
            "Refugee crises, asylum seekers, and displacement statistics",
            "Social movements, protests, civil rights, and activism worldwide",
            "Education policy, university research, and academic freedom debates",
            "Demographics trends, population changes, and urbanization patterns",
            "Gender equality, women's rights, and LGBTQ+ rights developments",
            "Housing crisis, homelessness, and affordable housing initiatives",
            "Religious events, interfaith dialogue, and church-state relations",
            "Human rights violations, international sanctions, and advocacy",
            "Labor migration, diaspora communities, and integration challenges",
            "Indigenous peoples' rights, land disputes, and cultural preservation",
            "Disability rights, accessibility legislation, and inclusion policies",
            "Child welfare, adoption policy, and children's rights advocacy",
            "Food insecurity, hunger crises, and global food aid programs",
            "Workers' rights, union organizing, and labor strike actions",
            "Racial justice movements, anti-discrimination efforts, and hate crime policy",
            "Digital divide, internet access inequality, and tech inclusion programs",
            "Aging population challenges, pension reform, and elder care policy",
            "Freedom of press, journalist safety, and media censorship incidents",
            "Urbanization challenges, megacity growth, and slum improvement programs",
        ],
    },
]

LANGUAGES = [
    ("en", "English", True),
    ("ru", "Russian", False),
    ("uk", "Ukrainian", False),
]
