"""Default digest sections with translations and embedding descriptions.

Used by the initdigest management command to seed the database.
Each section has ~10 embedding descriptions for broad news coverage.
"""

SECTIONS = [
    {
        "slug": "ai-technology",
        "order": 0,
        "description": "Artificial intelligence, big tech, gadgets, software, digital innovation",
        "translations": {
            "en": "AI & Technology",
            "ru": "AI • Технологии",
            "uk": "AI • Технології",
        },
        "embeddings": [
            "Artificial intelligence breakthroughs, new AI models, and machine learning advances",
            "Big tech companies: Apple, Google, Microsoft, Meta, Amazon news and strategy",
            "Semiconductor industry, chip manufacturing, and tech supply chains",
            "Social media platforms, content moderation, and digital regulation",
            "Space technology, satellite launches, and commercial space industry",
            "Tech startup funding, venture capital, and unicorn company valuations",
            "Robotics advances, automation technology, and industrial innovation",
            "AI regulation, ethics debates, and government tech policy",
            "Cloud computing, enterprise software, and digital transformation news",
            "Consumer electronics, gadgets, smartphones, and hardware launches",
        ],
    },
    {
        "slug": "world-politics",
        "order": 1,
        "description": "International relations, diplomacy, geopolitics, summits, treaties, sanctions",
        "translations": {
            "en": "World Politics",
            "ru": "Мировая политика",
            "uk": "Світова політика",
        },
        "embeddings": [
            "International diplomacy and foreign policy negotiations between world leaders",
            "United Nations resolutions, votes, and multilateral agreements",
            "NATO alliance decisions, military cooperation, and defense pacts",
            "Geopolitical tensions and rivalry between major world powers",
            "Economic sanctions, trade embargoes, and diplomatic pressure campaigns",
            "Presidential and prime ministerial summits and bilateral meetings",
            "International treaties, accords, and diplomatic breakthroughs",
            "Global governance reform and international institution changes",
            "Diplomatic crises, ambassador recalls, and embassy incidents",
            "Elections, referendums, and political transitions around the world",
        ],
    },
    {
        "slug": "business-economy",
        "order": 2,
        "description": "Global economy, stock markets, central banks, trade, inflation, corporations",
        "translations": {
            "en": "Business & Economy",
            "ru": "Бизнес • Экономика",
            "uk": "Бізнес • Економіка",
        },
        "embeddings": [
            "Stock market movements, Wall Street trading, and major index changes",
            "Central bank interest rate decisions, Federal Reserve, and ECB policy",
            "Global inflation data, consumer prices, and cost of living trends",
            "International trade agreements, tariffs, and supply chain disruptions",
            "Major corporate earnings, mergers, acquisitions, and business deals",
            "Oil and energy prices, OPEC decisions, and commodity markets",
            "Employment data, unemployment rates, and labor market trends",
            "Global economic forecasts, GDP growth, and recession indicators",
            "Banking sector news, financial regulation, and fintech developments",
            "Real estate markets, housing prices, and commercial property trends",
        ],
    },
    {
        "slug": "crypto-fintech",
        "order": 3,
        "description": "Cryptocurrency, blockchain, DeFi, digital payments, fintech startups",
        "translations": {
            "en": "Crypto & Fintech",
            "ru": "Крипто • Финтех",
            "uk": "Крипто • Фінтех",
        },
        "embeddings": [
            "Bitcoin price movements, halving events, and market dominance shifts",
            "Ethereum ecosystem, smart contracts, and layer-2 scaling solutions",
            "Cryptocurrency regulation, SEC enforcement, and global policy frameworks",
            "DeFi protocols, yield farming, liquidity pools, and decentralized exchanges",
            "NFT market trends, digital collectibles, and tokenization of assets",
            "Stablecoin developments, CBDC launches, and digital currency policy",
            "Crypto exchange news, Binance, Coinbase, and trading platform updates",
            "Blockchain technology adoption by enterprises and governments",
            "Fintech startups, digital banking, mobile payments, and neobanks",
            "Web3 development, DAOs, and decentralized governance experiments",
        ],
    },
    {
        "slug": "war-conflicts",
        "order": 4,
        "description": "Wars, military operations, armed conflicts, defense, security threats",
        "translations": {
            "en": "War & Conflicts",
            "ru": "Война • Конфликты",
            "uk": "Війна • Конфлікти",
        },
        "embeddings": [
            "Armed conflicts, wars, and military operations around the world",
            "Ceasefire violations, truce collapses, and escalation of hostilities",
            "Military weapons systems, defense technology, and arms deals",
            "Refugee crises and humanitarian disasters caused by conflict",
            "Nuclear weapons proliferation and disarmament negotiations",
            "Peacekeeping missions and international military interventions",
            "Intelligence operations, espionage scandals, and security breaches",
            "Civil unrest, coups, and political violence in unstable regions",
            "Defense budgets, military spending, and army modernization programs",
            "Peace negotiations, ceasefire agreements, and conflict resolution talks",
        ],
    },
    {
        "slug": "disasters-emergencies",
        "order": 5,
        "description": "Natural disasters, accidents, emergencies, catastrophes, rescue operations",
        "translations": {
            "en": "Disasters & Emergencies",
            "ru": "Катастрофы • ЧП",
            "uk": "Катастрофи • НС",
        },
        "embeddings": [
            "Earthquakes, tsunamis, and seismic activity causing destruction",
            "Hurricanes, typhoons, cyclones, and severe storm damage",
            "Wildfires, forest fires, and large-scale fire emergencies",
            "Flooding, landslides, and water-related natural disasters",
            "Aviation accidents, plane crashes, and air safety incidents",
            "Industrial accidents, factory explosions, and chemical spills",
            "Train derailments, maritime disasters, and transportation accidents",
            "Volcanic eruptions, geological hazards, and evacuation orders",
            "Rescue operations, emergency response, and disaster relief efforts",
            "Infrastructure collapses, building failures, and bridge accidents",
        ],
    },
    {
        "slug": "science",
        "order": 6,
        "description": "Scientific research, space exploration, physics, biology, discoveries",
        "translations": {
            "en": "Science",
            "ru": "Наука",
            "uk": "Наука",
        },
        "embeddings": [
            "Space exploration missions, NASA discoveries, and Mars exploration",
            "Physics discoveries, quantum computing, and fundamental science",
            "Astronomy discoveries, telescope observations, and cosmic phenomena",
            "Climate science research, environmental studies, and ecological findings",
            "Genetics research, gene therapy, and CRISPR technology advances",
            "Biology breakthroughs, evolution research, and species discoveries",
            "Chemistry and materials science advances and new compounds",
            "Ocean exploration, deep sea discoveries, and marine science",
            "Archaeology discoveries, paleontology findings, and historical research",
            "Nobel Prize announcements, major scientific awards, and research funding",
        ],
    },
    {
        "slug": "health-medicine",
        "order": 7,
        "description": "Medical breakthroughs, epidemics, public health, pharmaceuticals, mental health",
        "translations": {
            "en": "Health & Medicine",
            "ru": "Здоровье • Медицина",
            "uk": "Здоров'я • Медицина",
        },
        "embeddings": [
            "Medical research breakthroughs, new treatments, and drug approvals",
            "Pandemic monitoring, infectious disease outbreaks, and WHO alerts",
            "Vaccine development, clinical trials, and immunization campaigns",
            "Mental health research, psychology studies, and public health policy",
            "Cancer research, oncology breakthroughs, and treatment innovations",
            "Pharmaceutical industry news, drug pricing, and patent disputes",
            "Public health crises, healthcare system challenges, and hospital capacity",
            "Nutrition research, diet studies, and food safety regulations",
            "Organ transplant advances, surgical innovations, and medical devices",
            "Healthcare policy, insurance reform, and universal coverage debates",
        ],
    },
    {
        "slug": "crime-justice",
        "order": 8,
        "description": "Crime, law enforcement, court rulings, investigations, legal proceedings",
        "translations": {
            "en": "Crime & Justice",
            "ru": "Криминал • Правосудие",
            "uk": "Кримінал • Правосуддя",
        },
        "embeddings": [
            "Major criminal investigations, high-profile arrests, and manhunts",
            "Court rulings, landmark legal decisions, and Supreme Court cases",
            "Organized crime, drug trafficking, and cartel operations",
            "White-collar crime, fraud schemes, and financial scandals",
            "Police reform, law enforcement controversies, and use-of-force incidents",
            "Prison system news, incarceration rates, and criminal justice reform",
            "Terrorism investigations, extremist arrests, and counter-terrorism",
            "International criminal tribunals, war crimes trials, and extraditions",
            "Mass shootings, gun violence, and firearms legislation debates",
            "Human trafficking, smuggling networks, and cross-border crime",
        ],
    },
    {
        "slug": "cybersecurity-privacy",
        "order": 9,
        "description": "Cybersecurity, data breaches, hacking, privacy, surveillance, digital rights",
        "translations": {
            "en": "Cybersecurity & Privacy",
            "ru": "Кибербезопасность • Приватность",
            "uk": "Кібербезпека • Приватність",
        },
        "embeddings": [
            "Major data breaches, leaked databases, and personal information exposure",
            "Ransomware attacks on corporations, hospitals, and government agencies",
            "State-sponsored hacking, cyber espionage, and nation-state cyber operations",
            "Zero-day vulnerabilities, software exploits, and security patches",
            "Privacy legislation, GDPR enforcement, and data protection regulations",
            "Surveillance technology, facial recognition, and government monitoring",
            "Phishing campaigns, social engineering, and online scam operations",
            "Critical infrastructure cyberattacks on power grids and water systems",
            "Encryption debates, backdoor mandates, and digital rights activism",
            "Dark web marketplaces, cybercrime forums, and law enforcement takedowns",
        ],
    },
    {
        "slug": "energy-climate",
        "order": 10,
        "description": "Energy policy, renewable energy, climate change, environmental regulation",
        "translations": {
            "en": "Energy & Climate",
            "ru": "Энергетика • Климат",
            "uk": "Енергетика • Клімат",
        },
        "embeddings": [
            "Climate change policy, COP summits, and emission reduction commitments",
            "Renewable energy expansion, solar and wind power projects",
            "Oil and gas industry developments, drilling, and pipeline projects",
            "Nuclear energy policy, reactor construction, and atomic regulation",
            "Carbon capture technology, green hydrogen, and clean energy innovation",
            "Electric vehicles, EV charging infrastructure, and battery technology",
            "Environmental regulation, pollution control, and industrial emissions",
            "Extreme weather events linked to climate change and adaptation measures",
            "Energy security, supply crises, and geopolitical energy competition",
            "Deforestation, ocean pollution, biodiversity loss, and conservation efforts",
        ],
    },
    {
        "slug": "sports",
        "order": 11,
        "description": "Major sports leagues, Olympics, championships, transfers, records",
        "translations": {
            "en": "Sports",
            "ru": "Спорт",
            "uk": "Спорт",
        },
        "embeddings": [
            "Football (soccer) league results, Champions League, and World Cup news",
            "American sports: NFL, NBA, MLB, NHL scores and championship updates",
            "Olympic Games preparation, competition results, and medal standings",
            "Tennis Grand Slam tournaments, rankings, and major match results",
            "Formula 1 racing, MotoGP, and motorsport championship standings",
            "Transfer market news, player signings, and contract negotiations",
            "Sports doping scandals, anti-doping investigations, and athlete bans",
            "Boxing and MMA: major fights, title bouts, and combat sports news",
            "Cricket, rugby, and other international sports tournament results",
            "Sports business, broadcasting rights, stadium deals, and franchise values",
        ],
    },
    {
        "slug": "entertainment-culture",
        "order": 12,
        "description": "Movies, music, TV, celebrities, art, cultural events, media",
        "translations": {
            "en": "Entertainment & Culture",
            "ru": "Развлечения • Культура",
            "uk": "Розваги • Культура",
        },
        "embeddings": [
            "Movie releases, box office results, and film festival awards",
            "Music industry news, album releases, concerts, and chart rankings",
            "Television series premieres, streaming platform content, and ratings",
            "Celebrity news, scandals, and entertainment industry events",
            "Art exhibitions, museum openings, and visual arts events",
            "Book releases, literary awards, and publishing industry news",
            "Theater, Broadway, and performing arts events and reviews",
            "Video game releases, gaming industry, and esports tournaments",
            "Awards ceremonies: Oscars, Grammys, Emmys, and Golden Globes",
            "Streaming wars, content deals, and entertainment business mergers",
        ],
    },
    {
        "slug": "dev-opensource",
        "order": 13,
        "description": "Software development, open source projects, programming, developer tools",
        "translations": {
            "en": "Development & Open Source",
            "ru": "Разработка • Open Source",
            "uk": "Розробка • Open Source",
        },
        "embeddings": [
            "Open source project releases, major version updates, and community news",
            "Programming language updates, new features, and ecosystem developments",
            "Developer tools, IDEs, code editors, and productivity software",
            "GitHub trending projects, repository milestones, and community events",
            "Linux kernel development, distribution releases, and system administration",
            "Web development frameworks, frontend and backend technology trends",
            "DevOps practices, CI/CD pipelines, and infrastructure as code",
            "API design, microservices architecture, and software engineering practices",
            "Tech conferences, developer events, and hackathon results",
            "Database technology, data engineering, and distributed systems advances",
        ],
    },
    {
        "slug": "society-migration",
        "order": 14,
        "description": "Social movements, migration, demographics, education, human rights",
        "translations": {
            "en": "Society & Migration",
            "ru": "Общество • Миграция",
            "uk": "Суспільство • Міграція",
        },
        "embeddings": [
            "Immigration policy, visa regulations, and border control measures",
            "Refugee crises, asylum seekers, and displacement statistics",
            "Social movements, protests, civil rights, and activism worldwide",
            "Education policy, university research, and academic freedom debates",
            "Demographics trends, population changes, and urbanization patterns",
            "Gender equality, women's rights, and LGBTQ+ rights developments",
            "Housing crisis, homelessness, and affordable housing initiatives",
            "Religious events, interfaith dialogue, and church-state relations",
            "Human rights violations, international sanctions, and advocacy",
            "Labor migration, diaspora communities, and integration challenges",
        ],
    },
]

LANGUAGES = [
    ("en", "English", True),
    ("ru", "Russian", False),
    ("uk", "Ukrainian", False),
]
