# Generated by Django 6.0.3 on 2026-07-22 07:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('digest', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('website', models.URLField(blank=True, default='', max_length=2000)),
                ('description', models.TextField(blank=True, default='')),
                ('reliability', models.PositiveSmallIntegerField(default=3)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_entry_published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('lean', models.CharField(blank=True, choices=[('left', 'Left'), ('center_left', 'Center-Left'), ('center', 'Center'), ('center_right', 'Center-Right'), ('right', 'Right')], db_index=True, default='', max_length=20)),
                ('factuality', models.CharField(blank=True, choices=[('high', 'High'), ('mixed', 'Mixed'), ('low', 'Low')], db_index=True, default='', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='feed.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='location.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='core.language')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, default='', max_length=300)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Extracted'), (2, 'Completed')], db_index=True, default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('classified', models.BooleanField(db_index=True, default=False)),
                ('embedded', models.BooleanField(db_index=True, default=False)),
                ('section_score', models.FloatField(default=0)),
                ('sectioned', models.BooleanField(db_index=True, default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='digest.digestsection')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='feed.feed')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_topics', to='feed.article')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_topics', to='feed.topic')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', through='feed.ArticleTopic', to='feed.topic'),
        ),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='feed.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='feed_articl_article_7636f7_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'unique_together': {('article', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('conclusion', models.TextField(blank=True, default='')),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='feed.article')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='core.language')),
            ],
            options={
                'unique_together': {('article', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='articletopic',
            index=models.Index(fields=['topic', 'score'], name='feed_articl_topic_i_4404c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articletopic',
            unique_together={('article', 'topic')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'published'], name='feed_articl_feed_id_f45873_idx'),
        ),
    ]
