# Generated by Django 6.0.3 on 2026-03-24 12:34

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('website', models.URLField(blank=True, default='', max_length=2000)),
                ('description', models.TextField(blank=True, default='')),
                ('reliability', models.PositiveSmallIntegerField(default=3)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('lean', models.CharField(blank=True, choices=[('left', 'Left'), ('center_left', 'Center-Left'), ('center', 'Center'), ('center_right', 'Center-Right'), ('right', 'Right')], db_index=True, default='', max_length=20)),
                ('factuality', models.CharField(blank=True, choices=[('high', 'High'), ('mixed', 'Mixed'), ('low', 'Low')], db_index=True, default='', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='feed.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='location.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='core.language')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, default='', max_length=300)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('rss_content', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('content_fetched', models.BooleanField(db_index=True, default=False)),
                ('extract_error', models.CharField(blank=True, default='', max_length=500)),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('starred', models.BooleanField(db_index=True, default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('embedded', models.BooleanField(db_index=True, default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='feed.feed')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='feed.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='feed_articl_article_7636f7_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'unique_together': {('article', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('downloaded', models.BooleanField(db_index=True, default=False)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feed.article')),
            ],
            options={
                'unique_together': {('article', 'source_url')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'published'], name='feed_articl_feed_id_f45873_idx'),
        ),
    ]
