# Generated by Django 6.0.3 on 2026-03-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_articleimagesource_articleimage_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_fetched',
        ),
        migrations.RemoveField(
            model_name='article',
            name='embedded',
        ),
        migrations.RemoveField(
            model_name='article',
            name='extract_error',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read',
        ),
        migrations.RemoveField(
            model_name='article',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.CreateModel(
            name='ArticlePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_extracted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('images_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='feed.article')),
            ],
        ),
    ]
