# Generated by Django 6.0.3 on 2026-03-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_article_content_fetched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepipeline',
            old_name='images_fetched_at',
            new_name='og_images_at',
        ),
        migrations.AddField(
            model_name='articlepipeline',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepipeline',
            name='rss_images_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
