# Generated by Django 6.0.3 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_add_article_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articleimage',
            index=models.Index(fields=['is_primary', 'downloaded'], name='feed_articl_is_prim_9e6ea6_idx'),
        ),
    ]
