# Generated by Django 6.0.3 on 2026-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_articleimage_feed_articl_is_prim_9e6ea6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_entry_published',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
