# Generated by Django 6.0.3 on 2026-04-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_feed_last_entry_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rss_content',
        ),
    ]
