# Generated by Django 6.0.3 on 2026-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0029_remove_digestitem_image_digestitem_cover_article'),
        ('feed', '0008_remove_rss_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleimage',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='articleimage',
            name='feed_articl_is_prim_9e6ea6_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Extracted'), (2, 'Completed')], db_index=True, default=0),
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='source',
        ),
        migrations.DeleteModel(
            name='ArticlePipeline',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleImageSource',
        ),
    ]
