# Generated by Django 6.0.3 on 2026-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_articleimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='used_in_digest',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
