# Generated by Django 6.0.3 on 2026-07-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_article_used_in_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('conclusion', models.TextField(blank=True, default='')),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ru_summary', to='feed.article')),
            ],
        ),
    ]
