# Generated by Django 6.0.3 on 2026-07-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_active_to_language'),
        ('feed', '0011_articlesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesummary',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_summaries', to='core.language'),
        ),
        migrations.AlterField(
            model_name='articlesummary',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='feed.article'),
        ),
        migrations.AlterUniqueTogether(
            name='articlesummary',
            unique_together={('article', 'language')},
        ),
    ]
