# Generated by Django 6.0.3 on 2026-07-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_articlesummary_language_alter_articlesummary_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hidden', to='feed.feed')),
            ],
        ),
    ]
