# Generated by Django 6.0.3 on 2026-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_topic_alter_article_status_articletopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Extracted'), (2, 'Completed')], db_index=True, default=0),
        ),
    ]
