# Generated by Django 6.0.3 on 2026-07-21 07:03

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_article_classified_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='articlechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
