# Generated by Django 6.0.3 on 2026-07-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_article_embedded_alter_articlechunk_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiddenFeed',
        ),
    ]
