# Generated by Django 6.0.3 on 2026-07-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0036_alter_digestitem_options'),
        ('feed', '0017_delete_hiddenfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='digest.digestsection'),
        ),
        migrations.AddField(
            model_name='article',
            name='section_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sectioned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
