# Generated by Django 6.0.3 on 2026-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_article_section_article_section_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='used_in_digest',
        ),
    ]
