# Generated by Django 6.0.3 on 2026-03-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digest', '0001_initial'),
        ('feed', '0004_pipeline_split_images_add_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('search_queries', models.JSONField(default=list)),
                ('chunks_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='digest.digestitem')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.article')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.research')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
