# Generated by Django 6.0.3 on 2026-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_apiusage_digest_remove_apiusage_item_and_more'),
        ('research', '0002_add_language_to_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchsource',
            name='research',
        ),
        migrations.RemoveField(
            model_name='researchsource',
            name='article',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.DeleteModel(
            name='ResearchSource',
        ),
    ]
